### ISSUE TITLE
b.replace is not a function

### ISSUE THREAD

**Issue by Lux-Delux** [postmatic/epoch#1]
Downloaded 1.0.1 and on the front end I get this in chrome inspector

`b.replace is not a function` in epoch.min.js

Existing comments aren't rendered

**Comment by Shelob9** [comment]
@Lux-Delux Can you please pull the latest changes? It should be fine now.

**Comment by Lux-Delux** [comment]
I just reinstalled the plugin officially through wordpress and still the same problem.

However I did notice it works fine with the official theme. From some quick modifications I couldn't figure out what could go wrong (removed all comment related code and even disabling most js)

Any insight on why this error might occur would be appreciated, I'll try and track it down

**Comment by Lux-Delux** [comment]
Actually no, just tried submitting with default theme and doesn't work. I also get a 

`Failed to load resource: the server responded with a status of 409 (Conflict)` for the 

`epoch-api?epochNonce=2599612ec3&action=submit_comment Failed to load resource: the server responded with a status of 409 (Conflict)`

Does it have anything to do with me trying it out locally?  I'll test on live later

EDIT: same thing on live server. BTW on local I disabled all plugins so it's not a plugin conflict

**Comment by Shelob9** [comment]
@Lux-Delux Can you try flushing permalinks and trying again please?

**Comment by Lux-Delux** [comment]
Same thing after flushing permalinks

**Comment by Vernal** [comment]
Any progress on this, Josh?

**Comment by Vernal** [comment]
Hey Lux-Delux,

Can you grab Epoch 1.0 and let me know if this is still a problem?

Jason

**Comment by Vernal** [comment]
Hey @Shelob9 another user reported this error to me and I was able to replicate it. Here's a screenshot. Flushing permalinks didn't help. He has them set to Post Name.

![screen shot 2015-08-04 at 11 00 57 am](https://cloud.githubusercontent.com/assets/80932/9064063/c28795a2-3a98-11e5-8fce-263236c677fa.png)

I have wp-admin on the site in question and am able to test at will.

Active plugins (ignore wp-discuz):

![screen shot 2015-08-04 at 11 07 54 am](https://cloud.githubusercontent.com/assets/80932/9064144/2d40c60c-3a99-11e5-9f3c-01a73737c2d3.png)
![screen shot 2015-08-04 at 11 08 00 am](https://cloud.githubusercontent.com/assets/80932/9064148/314be22c-3a99-11e5-86b4-f5721a8013aa.png)

**Comment by Shelob9** [comment]
The var b, no idea what that is, must not be a string when minified. Hard
to say if this is merely a minification error or not.

Try setting SCRIPT_DEBUG to true to see if this really is an issue with
minification.

**Comment by Shelob9** [comment]
Close via 30b6739
