### ISSUE TITLE
set_comment_cookies filter lacks proper inline documentation

### ISSUE THREAD

**Issue by Shelob9** [postmatic/epoch#103]
This is displeasing to @shelob9

**Comment by ronalfy** [comment]
Docs should be in includes/default-filters.php. We're just re-using the filter. Still need docs?

**Comment by Shelob9** [comment]
Yes, the inline docs standards cover how to document a filter that is duplicated.

**Comment by ronalfy** [comment]
okay, would you mind tackling that if you don't mind?

**Comment by Shelob9** [comment]
Yep, It's assigned to me.

**Comment by ronalfy** [comment]
:D - Sorry, brain is fried and noticed that afterwards. My apologies.

**Comment by Shelob9** [comment]
I forgive you:)

**Comment by Vernal** [comment]
@JeffMatson this is up your alley, right?

**Comment by JeffMatson** [comment]
Yep. I'll do a docs run-through on it this weekend.

**Comment by Vernal** [comment]
Hells bells.

**Comment by JeffMatson** [comment]
This hook doesn't exist in 2.0-dev. Closing.

**Comment by Vernal** [comment]
Sweet. Thanks.
