### ISSUE TITLE
Replying to moderated comment is weird

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#105]
Currently moderators have the ability to reply to a comment that is still pending. We either need to make a reply trigger an approval.... or hide the reply link.

**Comment by Vernal** [comment]
For now i hid it via css and the behaviour is pretty nice. If you want to do something fancier go ahead. Otherwise close this issue.

**Comment by Shelob9** [comment]
Tricky. Shouldn't we make it so if an admin replies, it approves
automatically. I like that I can approve a comment by replying to a
Postmatic email notification on comment. Want same in Epoch.

**Comment by ronalfy** [comment]
I'm thinking if mod replies, and parent is moderated, change parent tobapproved.

Any caveats with this approach?

**Comment by Vernal** [comment]
Yea. If you can pull that off it would be awesome.

**Comment by ronalfy** [comment]
Can I place it on my buttons branch or create a new one?

**Comment by ronalfy** [comment]
You guys take too long. Fixed: https://github.com/postmatic/epoch/commit/1c38f1abfc3fb516c31b21895b316f1f57c35310

**Comment by ronalfy** [comment]
btw, the ^--- was insane sarcasm

**Comment by Vernal** [comment]
Jeeez oh man is this slick. But. The parent (moderated) comment needs to have its class switched to show it is approved. Right?

But yes. Otherwise. Awesome.

**Comment by ronalfy** [comment]
Fixed with https://github.com/postmatic/epoch/commit/b39cd5d162aa8b0880ab9954c03a9f6e854b76c0

**Comment by Vernal** [comment]
Get out of town.

On Fri, Sep 18, 2015 at 9:15 AM, Ronald Huereca notifications@github.com
wrote:

> Fixed with b39cd5d
> https://github.com/postmatic/epoch/commit/b39cd5d162aa8b0880ab9954c03a9f6e854b76c0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/105#issuecomment-141448586.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Oooh close. The approve button is still there though. Hrm. That's a
challenge.
[image: Inline image 1]

On Fri, Sep 18, 2015 at 9:16 AM, Jason G. Lemieux jason@vernalcreative.com
wrote:

> Get out of town.
> 
> On Fri, Sep 18, 2015 at 9:15 AM, Ronald Huereca notifications@github.com
> wrote:
> 
> > Fixed with b39cd5d
> > https://github.com/postmatic/epoch/commit/b39cd5d162aa8b0880ab9954c03a9f6e854b76c0
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmatic/epoch/issues/105#issuecomment-141448586.
> 
> ## 
> 
> Jason G. Lemieux | Creative Director
> Vernal Creative and Strategy
> http://www.vernalcreative.com | _New Number_ - 802.821.4059

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
Approve button fixed here: https://github.com/postmatic/epoch/commit/08b2a6257fbd4d4956b63c5108d2cfc38fb8bf12
