### ISSUE TITLE
Partially overwrites the output of the Sexy Author Bio plugin

### ISSUE THREAD

**Issue by ovizii** [postmatic/epoch#111]
The plugin is available from here: https://wordpress.org/plugins/sexy-author-bio/ and it looks like IF there are comments on a post, epoch overwrites the avatar size of bespoke plugin, if there are no comments, it does not overwrite the avatar size with its own.

Any chance you can fix this from your side or should I involve the other plugin author?

**Comment by Vernal** [comment]
Hey @ovizii I can't reproduce this. Can you share a url?

**Comment by ovizii** [comment]
hm, its been 2 months and I have just checked: the problem seems to have gone away.
there have been several epoch updates and a few for the other plugin, not sure what fixed it.

**Comment by Vernal** [comment]
Sweeet!

On Wed, Nov 25, 2015 at 4:04 AM, ovizii notifications@github.com wrote:

> Closed #111 https://github.com/postmatic/epoch/issues/111.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/111#event-474261695.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
