### ISSUE TITLE
The settings for Pings & Trackbacks don't seem to save properly

### ISSUE THREAD

**Issue by ovizii** [postmatic/epoch#120]
Check the box, click save, looks good.
Go to your dashboard then come back, the checkbox is gone.

**Comment by Vernal** [comment]
Noted! I think we should just default them to hidden, and add a hook to turn them on. Interested in amending this, @cklosowski ?

**Comment by Shelob9** [comment]
For the record it was saving properly, but the checkbox was not displaying properly. Fixed via 5594c33
