### ISSUE TITLE
Social avatars don't appear by comment box, interesting in like comment option

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#122]
Ticket submitted on behalf of noticiaspoliticas.net:

In default comment area of my theme, the facebook, twitter and G+ avatar appears correctly. But when activate epoch's they don´t. What can i do to the social avatars appears on epoch ?

One more thing: Like a comment doesn't exist on epoch? Are you thinking to put this on plugin?

**Comment by Vernal** [comment]
Legacy. Doesn't apply to 2.0.
