### ISSUE TITLE
Feature suggestion: add support for bbpress

### ISSUE THREAD

**Issue by ovizii** [postmatic/epoch#123]
That would be so awesome, imagine being able to reply to forums via email :-) 

Also, some people have replaced comment forms with bbpress and its apparently on the roadmap for the bbpress 2.6 release meaning.

**Comment by scholary-tim** [comment]
+1 indeed. That would be something else!

**Comment by Vernal** [comment]
I think you mean for this to be a features of Postmatic/Replyable. Noted!
