### ISSUE TITLE
Only enqueue scripts, styles and handlebars template when comment form is active

### ISSUE THREAD

**Issue by Jeradin** [postmatic/epoch#125]
Really enjoying your plugin, really good job!

I was curious if you have plans to only enqueue scripts when a comment form is active. 

Currently adding 4 extra scripts, templates and a style sheet that is only needed in one template of my site.

**Comment by Vernal** [comment]
For sure! This is part of the optimization work that we will be starting early next week. Are you able to lend a hand?

**Comment by Jeradin** [comment]
Totally! Will dig in a bit, I started to yesterday and should of gone forward and made a pull request! 

Thanks again for the work on this plugin.

**Comment by Vernal** [comment]
Cool. I would be interested to see what you came up with. We have a plan of attack for how we are going to do this, but haven't gotten around to doing it yet. Do you want to check in on what we've been thinking about before you really dig in?

**Comment by Jeradin** [comment]
Yes please.

-- 
Dale Jacobs

On October 15, 2015 at 10:16:30 AM, Jason Lemieux (notifications@github.com) wrote:

Cool. I would be interested to see what you came up with. We have a plan of attack for how we are going to do this, but haven't gotten around to doing it yet. Do you want to check in on what we've been thinking about before you really dig in?

**Comment by Vernal** [comment]
Sweet. Do you want to jump on skype or twitter to chat it out? I'm around until 5pm eastern:
skype: jlemieu
twitter: @gopostmatic

**Comment by Jeradin** [comment]
My apologizes for dropping the ball on this on Thursday, I am on a deadline to launch a new site and been doing 12 hour days. I should have time to connect after the beginning of this coming week.
