### ISSUE TITLE
Build in some spam protection

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#13]
We need to make Epoch happy to play with anti-spam, wordpress zero-spam, or some other front-end system.

**Comment by cyberhobo** [comment]
The simplest way to maintain compatibility with other front-end apps would be to use the native #commentform form ID instead of #epoch-comments-form. Do we use our own for styling reasons?

**Comment by Vernal** [comment]
At this point we may not need to put our own ID on that comment form. @Shelob9 is there any reason i can't change it on vars.php:60?

**Comment by Shelob9** [comment]
I switched it to `#commentform` leaving open for @Vernal to correct whatever that broke in our CSS. 

For the record,  `commentform` is the default value from `comment_form()` but it is a parameter that can be chaged, so those other plugins are `_doing_it_wrong()`

**Comment by cyberhobo** [comment]
There is a filter for the default ID, but none for the actual parameter
passed. So a plugin could reasonably be expected to adapt to a different
default ID, but not to one passed as the $id_form parameter to
comment_form(). We're in the same boat.
