### ISSUE TITLE
PHP notice - Screenshot attached

### ISSUE THREAD

**Issue by daronspence** [postmatic/epoch#132]
`Use of undefined constant EPOCH_ALT_COUNT_CHECK_MODE - assumed 'EPOCH_ALT_COUNT_CHECK_MODE'`

![screen shot 2015-10-27 at 3 29 25 pm](https://cloud.githubusercontent.com/assets/4062087/10771591/8b0f290a-7cbf-11e5-92d4-ee4af8324d8f.png)

Just popped up after the 1.0.8 update. De-activating and re-activating doesn't fix anything.

**Comment by Vernal** [comment]
Yep. Noted. Looking into it right now. Sorry.

**Comment by Vernal** [comment]
We will have a hotfix out for this asap. @Shelob9 is on it right now.

**Comment by Shelob9** [comment]
close via af1ce13

**Comment by Shelob9** [comment]
Also 1.0.8.1 on its way up to WP.org right now to fix this.

**Comment by daronspence** [comment]
Awesome! Thanks @Shelob9 & @Vernal
