### ISSUE TITLE
Comments Blacklist Problem

### ISSUE THREAD

**Issue by jakejackson1** [postmatic/epoch#133]
Using version 1.0.8.1, if you are using a blacklist of words `Settings -> Discussion -> Comment Blacklist` and a user enters a comment which has a blacklisted word the comment is added to the database but no comment text is saved.

**Comment by Vernal** [comment]
@erscampbell can you please test and verify this on qa?

**Comment by Vernal** [comment]
Hey @blueliquiddesigns we tested this extensively today and can't reproduce the problem.

In our tests if we enter a comment with a blacklisted word Epoch throws a message saying that the comment could not be submitted, and the comment shows up as a spam comment on the backend. 

The messaging that the comment was not accepted could certainly be improved.

What antispam and/or related commenting plugins are you running?

**Comment by jakejackson1** [comment]
Apologies. Yesterday I disabled the anti-spam plugins we were using and retested, but the issue appeared to persist. What I forgot to do was refresh the page and then test for issues (AJAX and all that).

It looks like a conflict with Epoch and the Antispam Bee (https://wordpress.org/plugins/antispam-bee/) plugin when a blacklisted word is present.
