### ISSUE TITLE
Epoch doesn't create a folder in WP-contnet

### ISSUE THREAD

**Issue by dkornyukhov** [postmatic/epoch#135]
Hey guys!
I've just installed your latest update and modified WP config file so that Epoch could enable txt-based server polling. But it doesn't seem to work on my website: https://theopenmic.co

I checked with my host and they say that everything is fine on their end, and also added:

"I have checked and the line in the wp-config.php file is added properly, but your plugin Epoch does not appear to be working normally. When it is being called, it returns the following error: Fatal error: Call to undefined method Composer\Autoload\ClassLoader::setPsr4() in /home/welovetr/public_html/theopenmic.co/wp-content/plugins/epoch/vendor/composer/autoload_real.php on line 33"

Moreover I see the following PHP notice:
Constant EPOCH_ALT_COUNT_CHECK_MODE already defined
Undefined offset: -1
wp-config.php:85

**Comment by Vernal** [comment]
Hey @dkornyukhov can you confirm you are on 1.0.8.1?

**Comment by dkornyukhov** [comment]
Yes, I am.

**Comment by Vernal** [comment]
Ok sorry about that. Looking into it now. I'll see if I can reproduce.

**Comment by dkornyukhov** [comment]
Thanks!

**Comment by Vernal** [comment]
Hrm. I can't reproduce the problem. Could you do me a favor and completely disable as well as delete Epoch, and then do a completely fresh installation of it? I hate to ask, but short of getting server access I'm not sure how to proceed. This might be the easiest next step.

**Comment by dkornyukhov** [comment]
Hi Vernal,
I just removed and re-installed Epoch. How else can I help?

**Comment by Vernal** [comment]
I'm guessing it didn't resolve the issue?

I'm going to have to summon @Shelob9 for his take on this. Any thoughts, Josh?

**Comment by dkornyukhov** [comment]
Ok, wait a second. Seems like Epoch created a folder in my wp-content/uploads. But it's empty. Is that how it supposed to be?

**Comment by dkornyukhov** [comment]
And I still see see the following PHP notice:
Constant EPOCH_ALT_COUNT_CHECK_MODE already defined
Undefined offset: -1
wp-config.php:85 on every page that has comments enabled.

**Comment by Vernal** [comment]
Oh good! We are making progress! The txt files are written once a post is
visited on the front end. Try it?!?!?

On Wed, Oct 28, 2015 at 12:10 PM, dkornyukhov notifications@github.com
wrote:

> Ok, wait a second. Seems like Epoch created a folder in my
> wp-content/uploads. But it's empty. Is that how it supposed to be?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/135#issuecomment-151895690.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Oh darn. Just saw you are still getting the error. I am going to go ahead and set up a site ground account to do my own testing. I'll update you this afternoon. Keep me up-to-date, as well.

**Comment by dkornyukhov** [comment]
Ok I tried viewing a couple of posts from front-end and even added a few comments. But the epoch folder is still empty.

**Comment by Vernal** [comment]
Hey again,

I set up a siteground installation today. The files are being written correctly but _something_ funky is going on. I'll keep poking it.

Jason

**Comment by dkornyukhov** [comment]
Thanks for the update, Jason. Meanwhile I've prepared Postmatic for localization :)

**Comment by Vernal** [comment]
Fantastic!

I've been working with Siteground and things are moving along. There is a
conflict with their Varnish cache... but I can confirm that for the
meantime regular server (database) polling works just fine. Will let you
know when I get things squared away with them.

Best,
Jason

On Thu, Oct 29, 2015 at 9:57 AM, dkornyukhov notifications@github.com
wrote:

> Thanks for the update, Jason. Meanwhile I've prepared Postmatic for
> localization :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/135#issuecomment-152188814.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Hello again!

The folks at Siteground were awesome enough to make this work over the weekend. I haven't written up the documentation yet but the quick of it is this: You'll need to enable supercacher and add an exception for Epoch. Done.

In the future even this step will not be necessary.... for now it is though.

Best,
Jason

![screen shot 2015-11-02 at 10 34 54 am](https://cloud.githubusercontent.com/assets/80932/10885865/79ec122c-814d-11e5-957d-d4e8aabc6af1.png)

**Comment by dkornyukhov** [comment]
Awesome, thanks for letting me know, Jason! Really loving the Postmatic! I have a few questions about Postmatic (some compatability issues with other plugin), but I'm going to send it over via your Support page. Thanks!
