### ISSUE TITLE
epoch comment plugin on wordpress - persistent loading icon

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#137]
## Ticket submitted on behalf of An Nguyen

Hi Postmatic team!

First, thank you for the great work so far! I have tried many comments systems on my site, and decided to settle on Epoch, although have yet to take the leap and utilize Postmatic as well.

My experience with the plugin has been nice and smooth, except for this loading icon that keeps showing up below the comments area. Commenting with my admin account logged in triggers a pop-up dialogue: "Your comment was not accepted, please check that everything was filled out correctly," but the comments show up above the icon after reloading the page. Loading a page with comments already on it also works.
I'm not sure what is happening?

![black dot](https://cloud.githubusercontent.com/assets/13645981/10888795/2d84d842-815c-11e5-867f-7f52aa7e2423.png)

Please excuse the non-English piece. The black dot is the culprit. I would really appreciate your help!

Thanks!
An

**Comment by Vernal** [comment]
It seems that this can be fixed by visiting settings > epoch and resaving the plugin settings. Still looking into why.
