### ISSUE TITLE
Problems with Epoch and reply to comments

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#140]
Submitting a ticket on behalf of Evgeniy Leytan:

Hi, when you turn "How agressively should Epoch override your default comment template" to "Completely (beta)" - reply to comments are posted as new comments. When you switch to "Use my typography and colors" replies are posted OK. Could you please fix that?

![screenshot](https://cloud.githubusercontent.com/assets/13645981/11003717/30e2c8ae-8482-11e5-96e6-9819e43316bb.jpg)

**Comment by Vernal** [comment]
Hey Evgeniy. That is because you are running both Epoch and Jetpack Comments at the same time. Very interesting, but not advised!
