### ISSUE TITLE
Epoch shows untranslated text "There are no comments"

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#146]
Hi Guys,
## Submitted on behalf of Edwin:

Today I installed Epoch (along with Postmatic) as a commenting system for my website
(http://fotenzo.com)

Somehow, there's some untranslated text above the comments form, that says:
"There are no comments" and "There's one comment", when somebody commented.
Although I have WPML running, I can not find the place to change this into Dutch.

The first should read "Er zijn geen reacties" and the second "Er is één reactie"
Is there a way to change this ? I know there's a way to change it through a .po file, but I'm not sure how to do this.

Cheers!
Edwin

**Comment by jankuziuk** [comment]
fsfdffd

**Comment by Vernal** [comment]
Legacy. Fixed in the upcoming 2.0.
