### ISSUE TITLE
Epoch and after entry widget

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#149]
Ticket submitted on behalf of Lise Galipeau:

---

I just installed epoch on a client's website, http://mountainbikediaries.com/copper-harbour/ to try it and it prevents the after-entry widget to show up, which should be between the post-meta and the comments.

if I deactivate the epoch plugin, then the after-entry widget shows up. So I'm stuck, can you please help. Would really love to use the epoch.

**Comment by Vernal** [comment]
Hey Lise,

Which plugin is calling the after-entry widget? Can you give me a
screenshot of what it is supposed to look like?

Jason

On Mon, Nov 30, 2015 at 12:44 PM, Elissa Campbell notifications@github.com
wrote:

> ## Ticket submitted on behalf of Lise Galipeau:
> 
> I just installed epoch on a client's website,
> http://mountainbikediaries.com/copper-harbour/ to try it and it prevents
> the after-entry widget to show up, which should be between the post-meta
> and the comments.
> 
> if I deactivate the epoch plugin, then the after-entry widget shows up. So
> I'm stuck, can you please help. Would really love to use the epoch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/149.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by SimplyLise** [comment]
Hi Jason,
The plugin I have in the after entry is a caldera subscription form.

If you look at my own blog, at the end of the post http://simplylise.com/easiest-tomato-pasta-sauce/
you will see the box with title Like what you read?  On my client's site, I'm using the same theme, foodie pro, and the same caldera form and the postmatic plugin and then now the epoch.  So the subscription form is supposed to show up between the post meta and the comments.

And you know, before trying Epoch, I tried the wpDiscuz and the same thing was happening...

Could it be something in the theme's code?

Thanks

**Comment by Vernal** [comment]
It could possibly be.. but the next question for me is _how_ are you
inserting the form there?

On Tue, Dec 1, 2015 at 9:01 AM, SimplyLise notifications@github.com wrote:

> Hi Jason,
> The plugin I have in the after entry is a caldera subscription form.
> 
> If you look at my own blog, at the end of the post
> http://simplylise.com/easiest-tomato-pasta-sauce/
> you will see the box with title Like what you read? On my client's site,
> I'm using the same theme, foodie pro, and the same caldera form and the
> postmatic plugin and then now the epoch. So the subscription form is
> supposed to show up between the post meta and the comments.
> 
> And you know, before trying Epoch, I tried the wpDiscuz and the same thing
> was happening...
> 
> Could it be something in the theme's code?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/149#issuecomment-160977675.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
And also... what are you using to make that nice little modal that pops on exit intent? I recognize it's a caldera form.. but what are you putting it inside?
![screen shot 2015-12-01 at 9 08 37 am](https://cloud.githubusercontent.com/assets/80932/11502886/6ccf4da0-980b-11e5-99e3-408742c7fe62.png)

**Comment by SimplyLise** [comment]
hold on just a sec and I'll go in and take a screenshot of the after entry

**Comment by SimplyLise** [comment]
So for the after entry widget, I created a caldera form and then I go to widgets, open the post bottom and drag the caldera form in there and choose which form to put there.  see the screenshot.

For the popup, it's a plugin called Popups - WordPress Popup and I created a popup and in the editor, I inserted the shortcode for the form. see the screenshot
hope this helps.
![popup-bottom-right](https://cloud.githubusercontent.com/assets/16087118/11503102/adce8220-980c-11e5-812a-210be1b8cb07.png)
![after-entry-screenshot](https://cloud.githubusercontent.com/assets/16087118/11503103/adcf5ee8-980c-11e5-9d0d-023e002da50d.png)

**Comment by SimplyLise** [comment]
Me again, I just did a test.  On my demo site, I installed Lifestyle theme and everything else: caldera forms, postmatic, postmatic for caldera forms and a form in the after entry.  And it's working fine,
see http://lisehosting.com/post-no-4/

So it's the theme but would you know which part in the code of the theme would affect the outcome?

thanks

**Comment by Vernal** [comment]
My hunch is that the theme is hooking that post-content sidebar into the
comments template... which Epoch doesn't use. You could work around that by
finding a plugin which let's you define a widget to place at the end of
your posts. There are tons and tons of them out there. There is also
Postmatic Optins as well.... you can find it in settings > postmatic >
options.

I love what you've done with that popups plugin and caldera forms. It's a
really elegant solution. May I blog about it?

Jason

On Tue, Dec 1, 2015 at 9:57 AM, SimplyLise notifications@github.com wrote:

> Me again, I just did a test. On my demo site, I installed Lifestyle theme
> and everything else: caldera forms, postmatic, postmatic for caldera forms
> and a form in the after entry. And it's working fine,
> see http://lisehosting.com/post-no-4/
> 
> So it's the theme but would you know which part in the code of the theme
> would affect the outcome?
> 
> thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/149#issuecomment-160990425.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by SimplyLise** [comment]
ok then, I'll see if I can find a plugin for that widget...what can I search in the plugin depository to find such a plugin?
If I remember I did try the postmatic optins, but I can't remember why I'm not using it, so I'll try again.

Well thank you for the nice compliment and yes of course you can blog about it :)

I'll keep you posted when I find a solution to the after entry. 
Thanks for all your help, you're great :)

**Comment by SimplyLise** [comment]
I got one :) and it works yeah!!! doing the happy dance
the plugin I got is called 'Add Widget After Content' and the form is showing and the epoch is also showing - see http://mountainbikediaries.com/my-new-blog-site/

Thank you so much again.

**Comment by Vernal** [comment]
Sure thing! That looks like a great plugin. Nice work!

**Comment by SimplyLise** [comment]
Thanks
