### ISSUE TITLE
Add admin option to have *engage in this conversation* checked by default

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#15]

**Comment by cyberhobo** [comment]
Are you talking about the Postmatic checkbox? Wouldn't that be a Postmatic option if so?

**Comment by Vernal** [comment]
I am talking about the Postmatic checkbox. I guess you’re right - it would make more sense to have it be a Postmatic option. Do you think we should do it there?

**Comment by cyberhobo** [comment]
That makes more sense to me. I'll todo it.
