### ISSUE TITLE
.epoch-pending only works on top level comments

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#155]
The new pending injector is awesome for top level comments but does not happen for replies.

**Comment by Shelob9** [comment]
@shelob9 -- Need to grab comment parent ID from the comment form markup and
put that into the comment object.

## 

JoshPress.net http://joshpress.net/
CalderaWP.com http://calderawp.com/
IngotHQ.com
@Josh412 http://twitter.com/Josh412

**Comment by Shelob9** [comment]
close via 9a5506a
