### ISSUE TITLE
How to make Epoch work when loading posts with AJAX

### ISSUE THREAD

**Issue by ghost** [postmatic/epoch#158]
Hey,

I am loading posts with their comments inside my website with Ajax.
- it might look like a bad idea, but it's what I have to do.

Could you please tell me how I can re-initialize the Epoch's js functions so it will work for each new post pulled with ajax?

thanks,
Razvan

**Comment by Vernal** [comment]
Hey saizeci - i'm not sure. There would be a whole lot of .js involved to make that happen.
