### ISSUE TITLE
Play nicely with recaptcha

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#16]
I tried various captcha plugins tonight and Epoch doesn't really work with them. It'll accept the comment no matter what. Oops.

**Comment by cyberhobo** [comment]
You can verify on the issue-16-recaptcha branch

**Comment by Vernal** [comment]
Fun. Did you try with a variety of plugins yet or should i?

**Comment by cyberhobo** [comment]
I did not.

**Comment by Vernal** [comment]
If the captcha fails epoch does not supply any feedback.. it comment form just kind of sits there.... can you hook into our existing validation setup?

**Comment by cyberhobo** [comment]
do you mean the alert that pops up if the comment is blank?

**Comment by cyberhobo** [comment]
Fixed in dc2c413396ed1c45c0048c2e6f8a79115d3c2ac4
