### ISSUE TITLE
Epoch not working correctly on mobile

### ISSUE THREAD

**Issue by dkornyukhov** [postmatic/epoch#160]
Hey guys,
I'm having a tiny problem with the way comments displayed on mobile. For some reason they're ignoring the device screen size limitations and turn out to be too long.
I suppose somthing is wrong with my CSS. Can you please check this out for me?

Here's a sample post: https://theopenmic.co/5-deevy-holiday-gifts-for-translators-and-interpreters/

Tested in iPhone 4

**Comment by Vernal** [comment]
Hey Dmitri,

Try this:

@media only screen and (max-width : 620px) { #epoch-wrap {width: inherit;} }

Jason

On Mon, Dec 21, 2015 at 11:20 PM, dkornyukhov notifications@github.com
wrote:

> Hey guys,
> I'm having a tiny problem with the way comments displayed on mobile For
> some reason they're ignoring the device screen size limitations and turn
> out to be too long
> I suppose somthing is wrong with my CSS Can you please check this out for
> me?
> 
> Here's a sample post:
> https://theopenmicco/5-deevy-holiday-gifts-for-translators-and-interpreters/
> 
> Tested in iPhone 4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/160.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by dkornyukhov** [comment]
Hey Jason!
Worked like a charm! Thanks a million, man! High-five from Toronto!

**Comment by Vernal** [comment]
Fantastic! Glad to hear. Lucky guess :)
