### ISSUE TITLE
Will you be able to support lazyload?

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#162]
Submitted on behalf of Frank Aune:

---

Also, we have articles that have 2000 or 3000 comments. Previously we used wpDiscuz which have lazyload to show more comments or show the readers a "load more comments" button.

**When I try to open our most commented article which have 3007 comments, Epoch does not handle it. That means we cannot use your plugin which is unfortunate as I love its integration with Postmatic. Will you be able to support lazyload or the possibility to add a "Show more comments" button? Soon?**

PS! Just before clicking send on this email, the comments eventually showed up, but that puts a big load on the server just by showing the post and the browser is strugglig as well. So it needs to be dealt with anyways as it took so long time that it didn't seem to work and puts an unneccesary load on the server which might affect all readers. Thanks!

Frank

**Comment by Vernal** [comment]
Hey Frank,

Epoch is not a good solution for posts with 3,007 comments. We don't offer lazyload and/or pagination yet. I'd say stick with wpDiscuz until we do.

wpDiscuz does offer perfectly great Postmatic integration. Give it a try!

jason

**Comment by TheArcturian** [comment]
Any idea when you will implement a "show more comments" button? Should be really easy to implement and will make Epoch, and hence Postmatic, much more attractive to bigger sites.
