### ISSUE TITLE
Problems with Epoch and theme compatibility

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#163]
Submitted on behalf of Scott Dunn:

---

I am using Tesla Themes Credo theme and when I enable Epoch it shoves the comments in to the widget area as you can see in the image below. Is there not a way that it uses themes built-in requirements? I understand that it is probably a theme limitation but curious nonetheless.

![scott dunn](https://cloud.githubusercontent.com/assets/13645981/12055390/b269986a-aefa-11e5-8b07-47d47d3142bd.png)

**Comment by Vernal** [comment]
Hey Scott,

You could probably fix this by applying some css to #epoch-wrap. Something like:

#epoch-wrap {width: 95% !important}

Best,
Jason
