### ISSUE TITLE
Use comments_clauses filter to improve new comments query

### ISSUE THREAD

**Issue by Shelob9** [postmatic/epoch#164]
In 1.0 when getting new comments we send highest ID, query for all comments then discard lower comment IDs. comments_clauses filter will let us filter WHERE clause of the SQL query and make it only get the comments we need. Less worried about query speed, and more about not having to do PHP sorting.

**Comment by Vernal** [comment]
Sweet.

**Comment by Shelob9** [comment]
The fact that this filter must exist and therefore the way Epoch 1.0
handles this is very dumb was a big part of why I couldn't sleep last night.
