### ISSUE TITLE
A CSS Issue

### ISSUE THREAD

**Issue by dkornyukhov** [postmatic/epoch#166]
Hey guys!
I messed up some CSS (again, _sigh_). Can you please take a look?
Here's a post where Epoch doesn't look nice: https://theopenmic.co/how-happy-are-translators-with-their-studies/
And here's how it supposed to be: https://theopenmic.co/how-happy-are-translators-with-their-studies/

I guess the problem with some custom CSS in that first post. Can you please take a look and point me in the right direction?
The width of Epoch should be around 700px, but something overwrites it and I can't figure out what. Thanks in advance!

**Comment by dkornyukhov** [comment]
Sorry, the post that has CSS issue is here: https://theopenmic.co/the-open-mic-in-november-2015/

**Comment by dkornyukhov** [comment]
Don't worry guys, I think I fixed it.

**Comment by Vernal** [comment]
Yayy! Sorry about that. It's been a busy couple of weeks.

Jason

On Tue, Jan 12, 2016 at 10:37 AM, Dmitry Kornyukhov <
notifications@github.com> wrote:

> Closed #166 https://github.com/postmatic/epoch/issues/166.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/166#event-512527257.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
