### ISSUE TITLE
 Comments show up very late or not at all epoch

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#167]
Submitted on behalf of Muhammad A:

---

Comments show up very late or not at all when a page is loaded.
Loading animation keeps running.

Screenshot of loading http://i.imgur.com/P3RRGh0.png

Is there a fix for this? Because with this problem people cannot see previously made comments.

**Comment by Vernal** [comment]
Hey Muhammad,

Can you try visiting settings > epoch, and just click on Save/Update
Settings and report back?

On Wed, Jan 6, 2016 at 2:39 PM, Elissa Campbell notifications@github.com
wrote:

> ## Submitted on behalf of Muhammad A:
> 
> Comments show up very late or not at all when a page is loaded
> Loading animation keeps running
> 
> Example link
> 
> http://darkwebnewscom/anonymity/vuvuzela-a-new-anonymity-tool-created-by-mit-researchers/
> [1]
> 
> Screenshot of loading http://iimgurcom/P3RRGh0png [2]
> 
> Is there a fix for this? Because with this problem people cannot see
> previously made comments
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/167.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by boxybox** [comment]
Hi Vernal. 

That did not fix it.  It happens on some pages.  The loading animation keeps going on. 

(The website URL cannot be shared publicly because it's a client website and NDA stops me from posting links publicly.  )

**Comment by boxybox** [comment]
Just checked the console while loading the problem page and http://domain-name.com/epoch-api   is 404.  Shows up in the console 5 times. 

Edit:  As long I stay on that page the errors in the Console keep increasing.   404   domain/epoch-api

How to fix this?

**Comment by boxybox** [comment]
Anyone?

**Comment by Vernal** [comment]
Hey There.

Try reading through these threads:
https://github.com/postmatic/epoch/issues/39
https://github.com/postmatic/epoch/issues/30

Sorry for the short reply. We are trying to keep our heads down while developing 2.0. Keep an eye out.

**Comment by boxybox** [comment]
Both the above threads did not solve the problem. I have removed the plugin.   For some reason this file shows 404 http://domain-name.com/epoch-api

Do you think this would be fixed or this issue is not important to warrant a fix?

**Comment by boxybox** [comment]
Do you think this would be fixed or this issue is not important to warrant a fix?

**Comment by Vernal** [comment]
Sorry it didn't work out for you.

It'll definitely be resolved in Epoch 2... which is about a month away.
Keep an eye on our blog.

On Wed, Jan 20, 2016 at 11:49 PM, boxybox notifications@github.com wrote:

> Do you think this would be fixed or this issue is not important to warrant
> a fix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/167#issuecomment-173450258.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
