### ISSUE TITLE
Click to edit doesn't work correctly

### ISSUE THREAD

**Issue by dkornyukhov** [postmatic/epoch#169]
Hey guys,
When I'm trying to edit a comment and click Save I see a spinning wheel and it just keeps spinning infinitely. But when I refresh the page I see that the comment has been updated. Is it a problem with Ajax or something? I have the latest versions of both plugins installed.

Here's a link to an example post: https://theopenmic.co/shaping-up-the-future-of-the-translation-industry/

Let me know if you can help me fix this one. Thank you!

**Comment by ronalfy** [comment]
Is this an Epoch issue or another plugin? I'm assuming Simple Comment Editing?

**Comment by Vernal** [comment]
Yea, I think you are right about that @ronalfy. Want to move this issue over to your repo?

**Comment by Vernal** [comment]
I believe the recent SCE release fixed this.
