### ISSUE TITLE
Insert default headline text

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#17]
Please set the default headline text to be 'Join the conversation'

**Comment by cyberhobo** [comment]
Should you still be able to remove it?

**Comment by Vernal** [comment]
Yes please.

**Comment by Shelob9** [comment]
@cyberhobo I use parse defaults on the display options

**Comment by cyberhobo** [comment]
Thanks @Shelob9. Changing the default text sort of works: it shows up on the front end, but not on the settings page. You can set a value on the settings page, and that will take over. If you delete that on the settings page, you get no headline.

That's on issue-17-headline-default - good enough for now @Vernal?

**Comment by Vernal** [comment]
Totally. Thanks guys.

**Comment by cyberhobo** [comment]
alright, i merged that branch to master
