### ISSUE TITLE
Saving changes on Option screen is not obvious

### ISSUE THREAD

**Issue by jaredatch** [postmatic/epoch#171]
If your view port isn't tall enough to display all the options users need to scroll down to get to the "Save Changes" button.

This just happened to me. Scrolled down, clicked saved. Nothing happened. Hmmmm. Weird. Click save again. Still nothing. I was about to open up inspector to see if something was nuking the ajax when I accidentally scrolled up... low and behold there was the "Updated Successfully" message (which auto disappears after X seconds, so if you don't scroll up fast enough you still won't see it).

This isn't a great experience and I imagine I'm not the only one who ran into the problem.

There needs to be some sort of message or alert at the bottom of the page as well so users know their save was processed correctly.

**Comment by Vernal** [comment]
Totally. Noted.

**Comment by Vernal** [comment]
Legacy. Fixed in the upcoming 2.0.
