### ISSUE TITLE
Do not show comment status on pages

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#18]
Look into how a theme knows to call comments_template or not and respect it?

**Comment by cyberhobo** [comment]
twentyfifteen does this:

``` php
// If comments are open or we have at least one comment, load up the comment template.
if ( comments_open() || get_comments_number() ) :
    comments_template();
endif;
```

That seems to work fine with Epoch active. 

The 'flat' theme has no such condition, and always calls comments_template() but uses the default template, which starts with this:

``` php
<?php if ( post_password_required() || ! comments_open() ) { return; } ?>
```

That has the odd effect that comments don't show at all when closed, even if some comments were left before they were closed.

The twentyfifteen behavior makes more sense to me - display nothing only when comments are closed and there weren't any left previously.

**Comment by cyberhobo** [comment]
Ok, you can verify that behavior on branch issue-18-closed-empty.

**Comment by Vernal** [comment]
looks great. merge.
