### ISSUE TITLE
What when there are hundreds of comments?

### ISSUE THREAD

**Issue by singhnsk** [postmatic/epoch#180]
Some of my posts have hundreds of comments with some even touching a thousand. Normally I have comments pagination enabled so the page doesn't get too lengthy. But with epoch, all the comments are loaded on the same page making the page take longer to load and also so bulky that some browsers on under powered PCs tend to freeze.
We need something like how Disqus only loads a limited number of comments or else Epoch isn't any good for sites which actually receive a lot of comments (where it really is needed).

**Comment by visualdatasolutions** [comment]
Epoch has good potentials to handle large volume of comments. I have made some customization to the javascript, api processes and initial loading template of Epoch to handle over 150K comments (English translations of bible verses)  nested under the same post, efficiently. with the help of some custom fields and indexing, it takes less than 50 ms to dynamically generate html code of 100 comments per page. page loading speed depends on network speed, and the page with comments should load within 2 or 3 seconds if opening from the US (the server is in the US). Here is the link to the demo post for testing. [English bible translations in public domain](https://tagnmap.com/the-holy-bible). the site is still under development before launching. It is also possible to load 1,000 comments per page with Firefox.

**Comment by Vernal** [comment]
Wow, that's fantastic. I'd love to see how you put this together. Will follow up in #189.

**Comment by Vernal** [comment]
Legacy. Fixed in the upcoming 2.0.
