### ISSUE TITLE
I can't add comments

### ISSUE THREAD

**Issue by Skain13** [postmatic/epoch#183]
I have a new install of Epoch in Wordpress 4.4.2. I tried with just entering my required fields (name and email) and also with Postmatic. Both failed. I checked with Firebug and found an error:

"NetworkError: 404 Not Found - http://www.terrispad.com/wp/epoch-api?epochNonce=65144e4e3a&action=submit_comment"

**Comment by Vernal** [comment]
Legacy. Fixed in the upcoming 2.0.
