### ISSUE TITLE
Multisite compatibility: File-based polling

### ISSUE THREAD

**Issue by CheesyUK** [postmatic/epoch#184]
The filename used to poll within multisite is still simply the post id.
Due to multiple blogs in multi-site, there will be multiple posts across the network with the same post id.
The filename should reflect the blog id as well as the post id.
Standard practice would be to use the uploads location:
files > blog_id > epoch > post_id.txt

**Comment by Vernal** [comment]
Legacy. Fixed in the upcoming 2.0.
