### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by ghost** [postmatic/epoch#186]
For some reason, I am unable to override most of the existing Epoch styles. 

**Example**
When trying to make the avatars circles I added the following code to my stylesheet:

`.epoch-comment-author-avatar img {
    border-radius: 50% !important;
}`

No changes. I inspected it in Chrome and could see that the style I added did not override the existing one.

This has happened to every style I've tried to edit _except_ for the epoch-wrap id.

Any ideas how to fix? Thanks!

**Comment by Vernal** [comment]
Hey Molly,

Epoch is purposefully full of heavy-duty css that is hard to override. Um. The upcoming version may make it easier...
