### ISSUE TITLE
ajax doesnt work if you use wp_query to get some posts and their comment sections.

### ISSUE THREAD

**Issue by saltnpixels** [postmatic/epoch#188]
I have a special page i made in my theme that queries and loads a few posts along with their comments using comments_template(). The posts are in tabs and can be view by clicking them. 

While epoch tries to work it seems to have a hard attack with the fact that 3 comment forms are being loaded.
Even if I load one post with wp_query and one set of comments it doesnt work right...

**Comment by saltnpixels** [comment]
I see... interesting it wont even load unless I allow comments for this page...
And even when the epoch script loads it has a heart attack that im allowing 3 posts with comment sections!!

Can I fix this?
I have 3 posts in three tabs. only one shows at a time using jquery but I need all comment areas to work!!

**Comment by Vernal** [comment]
Hey Saltnpixels,

That’s quite a tall order. I’m not sure Epoch is up to the job. If you figure out a fix we’d definitely accept a pull request.

Best,
Jason

On April 10, 2016 at 8:55:51 PM, saltnpixels (notifications@github.com) wrote:

I see... interesting it wont even load unless I allow comments for this page...
And even when the epoch script loads it has a heart attack that im allowing 3 posts with comment sections!!

Can I fix this?
I have 3 posts in three tabs. only one shows at a time using jquery but I need all comment areas to work!!
