### ISSUE TITLE
Is the project still under active development?

### ISSUE THREAD

**Issue by visualdatasolutions** [postmatic/epoch#189]
Hi @Vernal  and team,

I wonder if the project is still under active development since there isn't much going on in recent months except a few comments in reporting issues. I have made a few changes to Epoch (js, api processes and initial loading template) in my project  to handle larger volume of comments efficiently (well, over 155K comments in total under one post). see my reply comment in issue #180  for some performance figures on a modest vps with limited resources.  High level of customization is required so the modification is more suitable for a premium plugin or commercial consulting service.  please get in touch if this project is still alive, and you have plan to make it beyond a free plugin. 
regards. 
Oliver

**Comment by Vernal** [comment]
Hey Oliver,

That's a really cool demo. I'd love to see what you have going there.

To answer your question: yes, Epoch is still in active development but things have been quiet while we plan out and prepare to begin developing Epoch 2. There is a hackathon planned for May 16-20. Would you like to jump on Skype sometime soon to talk a few things over? We'd love your help if you are interested. You can [schedule something with me](http://gopostmatic.com/schedule) here.

Best,
Jason
