### ISSUE TITLE
Feature request for Epoch

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#193]
Posting on behalf of Joey Zehr:

---

Hi, I'm using your comment plugin on my site and one issue I'm seeing is when someone isn't logged in, it just asks for their name, email address and website without saying something like "or if you already have an account log-in here". Is there a way to add that in via the function file or something like that, so that I'm not editing the actual plugin files? I just don't want people to be confused and think they have to sign up for a new account.

Your advice is much appreciated!

Thanks!
Joey

**Comment by Vernal** [comment]
I think this will behave better in 2.0. Check back soon.
