### ISSUE TITLE
Override inline width

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#194]
Posted on behalf of webdevmattcrom (https://wordpress.org/support/topic/override-inline-width)

---

**1st post:**
Hi there, really enjoying Epoch on my personal site at the moment. Just one small issue I'm trying to overcome.

It looks like all of the templating options add an inline width to the #epoch-wrap div and in my case that width is fairly narrow. See here and you'll see that it's 600px, but I'd prefer it to be 100%
https://www.mattcromwell.com/cleaning-out-your-naked-shortcodes/

I know I can do an !important, but I'd rather avoid that. Thanks!

**2nd post:**
Sorry, to follow-up, I have added an !important rule now. But you'll notice that the style="width: 6oopx" is still there. Just FYI.

**Comment by mathetos** [comment]
Thanks for submitting the ticket for me. I'll follow the progress here.

**Comment by Vernal** [comment]
Yea, that’s the ol’ width sniffer doing its job to make the width of the comment area be the same as your content column. I fear that an !important is really the only way o override that at this point. Sorry it’s so !important to you to not use !important. Get it? GET IT?!!?

On May 2, 2016 at 2:10:28 PM, Elissa Campbell (notifications@github.com) wrote:

Posted on behalf of webdevmattcrom (https://wordpress.org/support/topic/override-inline-width)

1st post:
Hi there, really enjoying Epoch on my personal site at the moment. Just one small issue I'm trying to overcome.

It looks like all of the templating options add an inline width to the #epoch-wrap div and in my case that width is fairly narrow. See here and you'll see that it's 600px, but I'd prefer it to be 100%
https://www.mattcromwell.com/cleaning-out-your-naked-shortcodes/

I know I can do an !important, but I'd rather avoid that. Thanks!

2nd post:
Sorry, to follow-up, I have added an !important rule now. But you'll notice that the style="width: 6oopx" is still there. Just FYI.

**Comment by mathetos** [comment]
Ya, I guess technically that is the width of my content, so it's working exactly as expected. But in this case it makes more sense to be full-width of the container.

Can I request a filter for that as a feature request?

**Comment by Vernal** [comment]
You sure can. Noted for 2.0 (which we are doing a code sprint on in a few weeks).

J
