### ISSUE TITLE
Figure out how to handle 429s 

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#2]
Error 429 happens when you leave too many comments too quickly. We need to support it.

**Comment by Shelob9** [comment]
@Vernal Please define "support it". Do you want to allow comment flooding, or do you want better UI feedback?

**Comment by Vernal** [comment]
Sorry. We should not allow comment flooding, and should have some UI feedback in place to let the user know to slow down.

**Comment by cyberhobo** [comment]
Try branch issue-2-die-handling.

**Comment by Vernal** [comment]
closer

http://note.io/1AJLOAX

**Comment by cyberhobo** [comment]
should be mobeta now

**Comment by Vernal** [comment]
looks great
