### ISSUE TITLE
How to activate languages (epoch-de_DE.mo)

### ISSUE THREAD

**Issue by bbrunch** [postmatic/epoch#209]
Hi there, 

I really love to use epoch, but sadly there are strings that don't translate based on my WP setup - for example, there is a "There are no comments" message which I neither can get rid off nor can translate it..

I was searching the theme folder for hints and I just found the epoch-de_DE.mo and the epoch-de_DE.po - is there any chance to be able to activate a language file here? 

Epoch currently wins all the forum/thread battles when it comes to searching for the best comment plugin - but without a proper translation, it is hard to stick with it :(

**Comment by Vernal** [comment]
Fixed in 2.0.
