### ISSUE TITLE
Loading stuck

### ISSUE THREAD

**Issue by aisalama** [postmatic/epoch#210]
I would love to try this plugin on the website I'm developing right now, but  I do have some issues.

Have a look below. The problem is that the loading stuck and never end up showing the comments. I've disabled cache, another plugins for security purposes, and still the problem occurs.

Would be happy to get it to work,
Best regards

![screencapture-ctfehu-hostfree-pw-archives-865-1468081027555](https://cloud.githubusercontent.com/assets/20372502/16708894/9198025e-4601-11e6-9f4f-645ddcdd8aa1.png)

**Comment by japope** [comment]
I am having exactly the same problem. 

Epoch was working perfectly before, but have been having this issue since the last upgrade of WP - fairly certain that no other plugins were updated.

**Comment by TheArcturian** [comment]
We experience the same problem. It is a problem for many of our readers, but not all of them. Is it any workaround or fix for this?

Is the maybe_verify_origin function any related to this problem and if so, what needs to be done with the function to make the comments load properly?

It is a big problem for us so any feedback is appreciated. Thanks.

**Comment by lukecav** [comment]
@TheArcturian So does this issue happen with WP 4.7.2 in a default theme like Twenty Seventeen?

**Comment by Vernal** [comment]
hey @lukecav i can verify this does not happen on 4.7.2 on the 2.0 branch... which is really all we should be concerned with.

**Comment by TheArcturian** [comment]
No, it's a Premium theme. Running WP 4.7.2. What is the 2.0 branch? A coming Epoch 2.0 version I hope?

**Comment by Vernal** [comment]
Totally. We're working on it now and could always use more hands. See if [any of these](https://github.com/postmatic/epoch/milestone/16) get you excited? If so, let me know and I'll add you to the team.

**Comment by TheArcturian** [comment]
I would like access to the version without the issue, but we are running a live server for a lot of readers. Is the current 2.0 version stable enough for a production server?

**Comment by jb510** [comment]
I've been testing on staging/dev servers... I definitely would not put it on a production server sorry.

**Comment by TheArcturian** [comment]
Ok. How far away is it from release approximately? 1 month? 6 months? Just need something for the staff.

**Comment by jb510** [comment]
James might have target launch... but sooner if you contribute!

**Comment by TheArcturian** [comment]
Is there any estimate on when Epoch 2.0 is going to be released?
We are struggling hard with this spesific bug which makes a lot of readers frustrated on a daily basis.
If there is any workaround on this problem, please let me know. Thanks!

**Comment by TheArcturian** [comment]
Any approximate release date for Epoch 2.0? Anyone?
