### ISSUE TITLE
[v2] non-logged in query args are wrong or "Windows barfs all over?"

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#213]
Hey Josh,

Testing in windows and also Safari on a mac gives me all sorts of crazy. Try here:
http://postmatic-vernal1.c9.io/2016/08/16/illum-vel-eos-nihil/

![screen shot 2016-08-22 at 2 23 16 pm](https://cloud.githubusercontent.com/assets/80932/17866485/ae096d7a-6874-11e6-81c8-68e9ff602e67.png)

**Comment by Shelob9** [comment]
Close via       907d23c
