### ISSUE TITLE
Epoch Comment box too large on Adorable Genesis Child theme

### ISSUE THREAD

**Issue by janemanthorpe** [postmatic/epoch#214]
Hi
I having issues with the comment box being too large on my posts.
I am using Adorable Genesis Child theme.

I also using Postmatic Social sharing plugin which puts all the social media plugins on 
the comment box at far right handside. But because the comment box is too large, they do not show.

I have attached a screen shot of the comment box I have showing on my site.

Please can you tell me how to solve this thanks.

Jane
![epoch comment box](https://cloud.githubusercontent.com/assets/21256809/17997267/a452d5d2-6bc1-11e6-95bb-f0df3feeaa8e.png)

**Comment by jb510** [comment]
Jane - You'll want to reach out to Pretty Darn Cute Design for support with their theme or the WordPress.org support forums.  

Issues here on GitHub are for development of new versions of Epoch.
