### ISSUE TITLE
Disable submit button while thinking

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#22]
We're getting some reports that submitting comments when running certain caching plugins. Until we weed out what is going on can we apply an inactive class to the submit comment button on click?

**Comment by cyberhobo** [comment]
That's on branch issue-22-disable-submit if you want to try it.

**Comment by Vernal** [comment]
Looks great. Merge in.

On Mon, Jun 8, 2015 at 8:33 PM, Dylan Kuhn notifications@github.com wrote:

> That's on branch issue-22-disable-submit if you want to try it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/22#issuecomment-110181147.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
