### ISSUE TITLE
turn off commenting spam issues

### ISSUE THREAD

**Issue by saltnpixels** [postmatic/epoch#223]
every so often I get "your commenting too fast" or "comment did not work please fill out correctly"

How do I disable this stuff. I dont mind the quick commenting.
Im using it on a site where people are logged in and basically using the comment area as a chat system.

**Comment by saltnpixels** [comment]
oh... its a native wordpress thing huh...
add_filter('comment_flood_filter', '__return_false');

nevermind :)

**Comment by Vernal** [comment]
sweet :)
