### ISSUE TITLE
Change comment form label from "Post Comment"

### ISSUE THREAD

**Issue by saltnpixels** [postmatic/epoch#225]
Would be nice if we can change the label for the button on comment form. This right now cannot be done without editing the plugin...

**Comment by cyberhobo** [comment]
There is a way to customize language for any plugin, outlined for The Events Calendar [here](https://theeventscalendar.com/knowledgebase/how-to-override-plugin-language-files/).

**Comment by saltnpixels** [comment]
what?
im not sure what you mean. I am talking about changing the submit form label from Post comment to Send or something...

**Comment by cyberhobo** [comment]
Ah, right, it's just the WordPress comment form. WordPress does provide [a filter](https://developer.wordpress.org/reference/hooks/comment_form_defaults/) for modifying it, but no settings.

**Comment by saltnpixels** [comment]
Yeah but it gets overridden by epoch.
I use comment_form. And I've set it but epoch overrides on layout.php

**Comment by cyberhobo** [comment]
This works for me: 

```php
add_filter( 'comment_form_defaults', function( $defaults ) {
	$defaults['label_submit'] = 'Foo';
	return $defaults;
} );
```

That's just WP though, works with or without epoch.

**Comment by saltnpixels** [comment]
I cant seem to override epoch with this. Are you sure it worked for you with epoch installed?

**Comment by cyberhobo** [comment]
It does, with all three of the template options. I'm not sure what might interfere with it, possibly the theme or another plugin.
