### ISSUE TITLE
When is it finally being released?

### ISSUE THREAD

**Issue by romtim** [postmatic/epoch#226]
We've asked for support with Epoch 1 half a year ago, and support told us that Epoch 2 is being released within a few weeks, so you do not support Epoch 1 anymore.

It's been half a year. There is no movement here since October.

Is development canceled?
Please let us know.

**Comment by Vernal** [comment]
Hey romtim,

Sorry for the delays. We're ramping up development again now. I'll be marking a number of issues here as helpwanted if you care to jump in and lend a hand.

Best,
Jason
