### ISSUE TITLE
Think through anonymization features

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#229]
hey @jekkilekki. I like your idea of making it a bit more possible to comment anonymously using Epoch. Do you want to head up researching the possibilities?

In the context of web commenting the best the user can hope for is an easy for for their personal information to not be presented on the front end, and to be able to leave a comment without leaving their email address. Actual anonymization is of course impossible here.

That said, let's start by looking at what facets of the traditional commenting experience present hurdles to commenting without an identity. In particular they are:

1. Name
2. Email Address

What would an anonymous experience look like? Just the ability to submit the form without filling out name and address fields, and have attribution be to a generated persona? Where else can we go with this?

**Comment by andykillen** [comment]
Where I work, we have 17 websites in a mix of Drupal and WordPress.  Every single site allows for anonymous commenting.  All sites deal with emotive subjects over Sexual Health, Democracy, Free speech, thus people need to be able to do things without people knowing.  Some examples: Comment on a article about AIDS expressing worry that they might have caught it; Comment on an article that goes against the government in a country where the government regularly makes people disappear; Comment against an article that carries a strong point of view where the country is divided based on political belief to the point of bloodshed. 

**Not Logged in**

Users can make a comment, they have max of 3 fields to fill

- Name
- Subject
- Message/Comment

When users are not logged in and commenting we highlight this that they are not necessarly the same person of the same name who is logged in when commenting.  We point out that people might be trying to create fake accounts to pervert the words of others. We also use an avatar that re-enforces this. 

**Logged in**
We offer two different situations here.  When logged in they can comment in their own name, which is automattically added to the comment form, or they can choose to put in a pseudonym.

Fields

- Name (from logged in profile) with Gravatar next to it
- Alias, optional to be filled in 
- Subject
- Message

On many of the sites we don't expect Subject to be used. We do however promote the idea that if they sign in that they can add power to their voice. We offer that sign in/register as a modal window sign up. so they don't ever get taken away from the comment.

**Comment by Vernal** [comment]
Hey @andykillen! 

Thank you so much for sharing this. I think that some of these ideas could certainly add civility to conversations. 

I wonder if this might just be an entirely different plugin (which could work well on top of Epoch). I say that because there are a few parts of it which go beyond the parts of WordPress we want to touch with Epoch.

I think that the balance you strike between pseudo-anonymity (logged out) and semi-verified identity is cool. And I can see the most value for civil conversation coming from by having users log in. That said, said plugin should address the user creation/verification experience. My first inclination is to use the comment form itself as the user registration. 

1. The user fills out a name, email, and their comment (just like always). 
2. The comment is held _somewhere_ until the user verifies their email address. 
3. A _subscriber_ user (or maybe even a new role) is created in wp upon verification.
4. The user is emailed their login info
5. Then, the comment goes to moderation (if appropriate) or publish. 

That would make for a quick and easy way for registration and commenting at the same time... and maybe would increase the amount of verified identities. 

Also hiding in there would need to be perhaps some sort of slick front-end login system, as well as all the details around security. 

On the logged-out side you could of course not require email address. And with comment_meta being available now adding a subject line to the comment form would be relatively easy as well.

Anyway. I think it is a whole other plugin. I'm happy to help with it and ensure it works well on top of Epoch. I'm going to close the issue... but ping me if you want to talk further.

Jason
