### ISSUE TITLE
Add support for .bytheauthor

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#23]
For the author.

**Comment by dknauss** [comment]
That would be great. Any chance you could add classes for each of the standard user roles, if only to indicate which commenters are subscribers via Postmatic or something else? It would be great to be able to recognize subscribers, contributors, authors and maybe editors and admins on multi-author sites.

**Comment by Vernal** [comment]
We'll take it into consideration. Thanks, Dan!

On Sat, Jul 25, 2015 at 7:59 PM, Dan Knauss notifications@github.com
wrote:

> That would be great. Any chance you could add classes for each of the
> standard user roles, if only to indicate which commenters are subscribers
> via Postmatic or something else? It would be great to be able to recognize
> subscribers, contributors, authors and maybe editors and admins on
> multi-author sites.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/23#issuecomment-124917128.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by solhuebner** [comment]
:+1:

**Comment by Vernal** [comment]
hey @cyberhobo going to hand this one off as well. Here is the spec:

Add .bypostauthor to comment.html:3 if appropriate.

Do you think that appending an additional class for user role (as mentioned by @newlocalmedia) would lead to a big database hit? Thoughts on that?

**Comment by cyberhobo** [comment]
Should be working on 1.0.2-dev. Adds one more query, but existing queries for each commenter are more likely to be an issue in the future.

**Comment by Vernal** [comment]
Yea that's pretty slick. Nice going. I'll work on some styles and then wrap it up.
