### ISSUE TITLE
Overhaul?

### ISSUE THREAD

**Issue by JeffMatson** [postmatic/epoch#230]
Overall, the codebase is a bit of a mess. What's everyone's thoughts on cleaning it up and doing a bit of refactoring?

The consensus between myself, @Vernal, and @Shelob9 seems to be that it needs some love.

Anyone want to pitch in on this?

**Comment by Vernal** [comment]
Yea, the 2.0 branch is the product of a couple of sprints but the overall architecture is sound and thought through by @Shelob9. Working with comments is tricky and a few decisions were made that, while not ideal, were the right direction to go in.

I think that if you want to do a refactor of the 2.0-dev you should do it on a new branch. We already have issues created and assigned against 2.0-dev and should at this point keep working there and iterate as we go.... then circle back?
Let's touch base on twitter or slack though so I can see where you want to take it.
