### ISSUE TITLE
Epoch is not respecting comment depth

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#24]
It seems that Epoch isn't listening to the set comment depth as defined in settings > discussion. See an example of that here:
http://www.autosvezzamento.it/

**Comment by Vernal** [comment]
Hey Josh, Please take a look at this when you can. Nudge.

**Comment by Vernal** [comment]
Hey Josh,

I can confirm this is happening on my test install as well. We can't release 1.0 until this is resolved.

Jason

**Comment by Shelob9** [comment]
close via 16572e2
