### ISSUE TITLE
Epoch makes comments disappear from the Make theme in IE 11

### ISSUE THREAD

**Issue by dknauss** [postmatic/epoch#26]
Theme Foundry's Make theme will not display existing comments in IE 11 if Epoch is active, whether its styling is enabled or not. (Tested using Make theme with the Make Plus plugin.)

**Comment by Vernal** [comment]
Hey Dan,

Thanks for letting us know. Epoch 1.0 will be out on Monday and i'm willing
to bet it will solve ie11 issues.

J

On Sat, Jul 25, 2015 at 1:19 PM, Dan Knauss notifications@github.com
wrote:

> Theme Foundry's Make theme will not display existing comments in IE 11 if
> Epoch is active, whether its styling is enabled or not. (Tested using Make
> theme with the Make Plus plugin.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/26.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by dknauss** [comment]
Let's hope so. Thanks!

**Comment by Vernal** [comment]
Hey Dan,

Give this a try for me now that 1.0 is out?

J

**Comment by dknauss** [comment]
Yeah, I tested that right away. It's fine now.

_Dan Knauss_
newlocalmedia.com
design. build.. sustain...
+1 712 449-8195 ✆ +1 414 212-5628
