### ISSUE TITLE
Iframe is somehow inheriting styles from the active theme

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#29]
I kid you not. It happens at least on the colorway theme. Seriously.
What do you make of this?

![screen_shot_2015-07-25_at_3_05_11_pm](https://cloud.githubusercontent.com/assets/80932/8890871/f04caf16-32de-11e5-953b-51c3b1142de0.png)

**Comment by Vernal** [comment]
If i visit single/epoch i can see where it is pulling the stylesheet of the parent. Check it out here:
http://pastebin.com/wpYH3Y6W

**Comment by Shelob9** [comment]
Closing via 
663d93662a414f954ac4fab348572b65f5fec4e1
0b8f152a5796a1732b46adbc7f073549e93524f7
9558608b77dce8e40b951d68145d3a4502eeb62a
bcac12467d657ced63985ee7f5d2e55370afb249
68fa05dfd70cde9445bde4357499d4829df8f3d2
