### ISSUE TITLE
Google is tracking epoch-api?replytocom= links 

### ISSUE THREAD

**Issue by dknauss** [postmatic/epoch#30]
Generates a lot of 404s in webmaster tools:
![crawl2](https://cloud.githubusercontent.com/assets/273554/8891887/c5cb7364-32ff-11e5-99c2-e95c576a6929.png)

**Comment by Vernal** [comment]
Josh, I've heard of this from a few other folks as well. What do you make of it? What can we do about it?

**Comment by dknauss** [comment]
Google WMT is picking these up as 403 and 404 errors for smartphones on one site with 2,400 posts at a ratio of 7:500 -- about 350 403s and 25,000 404s.

**Comment by iagdotme** [comment]
I've had this problem too. I ended up having to block epoch-api from my robots.txt file.

**Comment by Vernal** [comment]
We need to figure out how to address this. @newlocalmedia robots.txt might be a bandaid.

**Comment by dknauss** [comment]
Isn't the deeper issue the fact that /epoch-api is being called so much and sometimes producing 404s? It is a significant performance hit. For example, today so far on a site that normally averages 3-5k visits per day there have been 18,000 pageviews resulting in 115,000 requests for /epoch-api that resulted in a 200 response and 45,00 that resulted in a 404.

**Comment by dknauss** [comment]
The performance degradation on the right side of the attached chart starting in July corresponds to use of Epoch with a steady average of ~3k visits per day over the period shown. 

![screenshot 2015-09-14 15 43 02 - copy](https://cloud.githubusercontent.com/assets/273554/9866627/1e1a6b90-5b2a-11e5-92c9-2a02e3adb475.png)

**Comment by Vernal** [comment]
Hey Dan,

I'd like to try to wrap my mind around this. Can we jump on the phone or
skype sometime and compare notes? Hit me up at
http://gopostmatic.com/schedule if you have a minute?

Best,
Jason

On Mon, Sep 14, 2015 at 10:49 PM, Dan Knauss notifications@github.com
wrote:

> The performance degradation on the right side of the attached chart
> starting in July corresponds to use of Epoch with a steady average of ~3k
> visits per day over the period shown.
> 
> [image: screenshot 2015-09-14 15 43 02 - copy]
> https://cloud.githubusercontent.com/assets/273554/9866627/1e1a6b90-5b2a-11e5-92c9-2a02e3adb475.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/30#issuecomment-140262033.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by dknauss** [comment]
Will talk to you Thursday afternoon.

**Comment by Vernal** [comment]
Notes from our call:
The 404s in webmaster gools seems to not happen universally. I can't reproduce it on multiple sites which have similar setups (running Epoch, using Make). 
One notable difference between the site experiencing the problem and my own is that the permalinks were set to the post name instead of date/post. Maybe that's something. 

Site in question is hosted at lightningbase. I'll set up some sites there to test.
http://lightningbase.com/

Also to do: @newlocalmedia will enable Epoch on trouble site, set the server poll time to be nice and high, and we'll bat some comments back and forth to see if the visibility api is working.

**Comment by dknauss** [comment]
High as in low? I've set up a test with Epoch active at 1s polling on a test site on the same account as we discussed -- I'll email you the details. We may not need to bother, however, if I'm right about what's been going on.

I have an idea as to what the problem is now. These crawl errors were coming up on totally different environments with very different caching methods. Then, after disabling Epoch, I could see we were still getting unusual crawl errors for logout links and other stuff in the admin bar. Since we're also using Mark Jaquith's Cache Buddy plugin, that explains why this is happening. Since Cache Buddy also acts on comment forms, it's probably adding Epoch code to the cached page that normally would be served to logged-in users only. Google is trying to follow some of the links it sees in that code. 

Cache Buddy: https://markjaquith.wordpress.com/2015/03/27/cache-buddy/.

**Comment by Vernal** [comment]
Very interesting about cache buddy. We'll check it out.

As in high I mean set it up high... something like 30 or 60 seconds. Let's
jump on skype this afternoon.

On Mon, Sep 21, 2015 at 10:39 AM, Dan Knauss notifications@github.com
wrote:

> High as in low? I've set up a test with Epoch active at 1s polling on a
> test site on the same account as we discussed -- I'll email you the details.
> 
> I have an idea as to what the problem is now. These crawl errors were
> coming up on totally different environments with very different caching
> methods. Then, after disabling Epoch, I could see we were still getting
> unusual crawl errors for logout links and other stuff in the admin bar.
> Since we're also using Mark Jaquith's Cache Buddy plugin, that explains why
> this is happening. Since Cache Buddy also acts on comment forms, it's
> probably adding Epoch code to the cached page that normally would be served
> to logged-in users only. Google is trying to follow some of the links it
> sees in that code.
> 
> Cache Buddy: https://markjaquith.wordpress.com/2015/03/27/cache-buddy/.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/30#issuecomment-142002115.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Notes from call: problem seems to have cleared up with cache buddy disabled. Let's keep an eye on it some more....

**Comment by iagdotme** [comment]
Thanks guys for looking into this. Could you let me know the outcome? Has this been fixed?
I've been seeing high volumes of requests to epoch-api in my server logs and also Google tracking this.

**Comment by dknauss** [comment]
We're still investigating it. What are your hosting and plugin/install details?

On Sat, Sep 26, 2015 at 3:51 AM, Ian Anderson Gray <notifications@github.com

**Comment by dknauss** [comment]
@Vernal -- I'm not getting any of the crawl errors from Google WMT now, but there is still a significant performance hit (with 3-5k+ unique visits per day) from three POST requests to /epoch-api that occur on every pageload.

**Comment by Vernal** [comment]
Hey Guys,

I'm going to close out this issue. I've created a number of new issues to address performance and overly-excited api calls. You can find them here:
https://github.com/postmatic/epoch/labels/performance

Keep an eye on that label for some info as to what our next steps are going to be for this....
