### ISSUE TITLE
What about vendor folder ?

### ISSUE THREAD

**Issue by yafred** [postmatic/epoch#33]
Hi,

Very nice plugin. Thanks for that. 

When you install it from github, vendor folder is missing and gives a nasty error when plugin is activated.

I see that vendor folder is ignored on purpose (.gitignore) ... why ?

Thanks

**Comment by Vernal** [comment]
Handing this off to Josh...... Josh, can you address this and maybe also make some documentation as to dependencies?

**Comment by Shelob9** [comment]
@yafred The vendor folder is for the dependencies, and is managed by a dependency manager. It doesn't make sense to commit dependencies to the git repo.  If this is a problem, please install via WordPress.org.

**Comment by yafred** [comment]
@Shelob9 I see where you're coming from.

I think it's a good idea to keep the integrity of the plugin on github to be able to use tools like https://wppusher.com/ to stay in sync without cloning the repo.

However, I respect your choice
