### ISSUE TITLE
[via wordpress.org support forum] Slow site and Host blocked the epoch requests

### ISSUE THREAD

**Issue by senlin** [postmatic/epoch#36]
Originally reported by user [ls41](https://wordpress.org/support/profile/ls41) via [wordpress.org support forum](https://wordpress.org/support/topic/slow-site-and-host-blocked-the-epoch-requests)

After I installed Epoch, site load time decreased dramatically.

Today, I got this message from my host:

Upon investigation, we found that this is being caused by the 'epoch' plugin within WordPress. Since this morning there have been over 56,000 requests for the '/epoch-api' resource on this site. To reduce the load on your server and improve your sites performance, I have blocked these requests by adding the following lines to .htaccess:

```
<IfModule mod_rewrite.c>
RewriteCond %{REQUEST_METHOD} POST
RewriteCond %{REQUEST_URI} /epoch-api [NC]
RewriteRule .* - [F,L]
</IfModule>
```

I recommend that you disable the 'epoch' plugin to further reduce the impact that this plugin has on your sites performance.

**Comment by Shelob9** [comment]
Obviously, once they put that `mod_rewrite` rule in place, the plugin isn't going to work.

What kind of traffic did you have during the time this was active and how many comments did you have on your popular posts? Did your host provide any data on the actual resource consumption?

By default, this plugin makes 4 requests per minute, per page that is currently being viewed (we use the Visibility API to shut down when the tab isn't in focus) per user to check on the server if there are new comments. 

Lots of requests does not categorically equal lots of resources, but if you have a lot of comments, and a lot of traffic that could put a strain on your server. You could increase the interval in the options to have it run less frequently. Also, you just might wish to upgrade your hosting.

**Comment by DavidCramer** [comment]
Perhaps set a minimum check time. I wont be surprised if the site in question had it set to 1 or 0

**Comment by senlin** [comment]
@Shelob9 - Obviously I don't know any of the details, I only posted this issue, because you guys don't use the support forums over at wordpress.org and that is where this issue was posted originally about a month ago. 

Since WP Tavern published an article yesterday about your plugin, you can expect the amount of downloads to rise rapidly and I would want to think that an issue like this, then should be resolved asap...

Especially since one of your developers is quoted by saying:

> “The second reason is that native commenting is extremely hard on the server. You can’t run native comments on a high traffic site. The server would buckle. A CDN won’t save you because the page content is constantly changing. For larger sites, native commenting is not even an option.
> 
> “... the performance gains are minimal when the embedded comments still take 10 second to load because there is so much tracking JavaScript being queued up in the background.”
> 
> In contrast, Epoch loads faster than third party solutions ...
> 
> “For the first time someone can say this: running native WordPress commenting will actually increase your site performance,” Lemieux said.

[article on WP Tavern](http://wptavern.com/postmatic-brings-100-realtime-commenting-to-wordpress-with-epoch-plugin)

**Comment by Vernal** [comment]
Hey Senlin,

Let's start with this: what's going on at the server level? What was your traffic like during this time? Any rough stats you can share? Is this a _huge_ site with millions of uniques..... a medium site... or a small site? 

Also, what was the check frequency set at in the Epoch settings?

And, since the issue was reported a long time ago (and we didn't notice it on wp.org) it could have been resolved by now.

What more can you tell us?

Jason

**Comment by cyberhobo** [comment]
Epoch does short polling and will generate a lot of ajax requests, but as a start it uses the [page visibility api](https://github.com/ai/visibilityjs) to minimize polling. There are plenty of servers holding up fine with this, but I am curious to see how it does on a greater variety.

Eventually I think Epoch will have to figure out a long polling or web sockets solution, which will entail the same issues the core team ran into when [they tried to solve the problem](https://core.trac.wordpress.org/ticket/23216) for the heartbeat API. I'm not up to speed on that yet, but my hunch is that with PHP 5.3 and some stricter server requirements it can be done.

**Comment by senlin** [comment]
@Vernal 
With all due respect, but which part of

>  Originally reported by user ls41 via wordpress.org support forum

did you not understand?

I have only posted that issue here of **this other user** for the simple reason that you don't offer support via the wordpress.org forums and because I think the issue is important enough to get attention.

**Comment by Vernal** [comment]
Ahhhhhhh! The part I didn't understand was that ls41 was not you! Very sorry. Moving too quickly.

Well. I'm not sure where to go with this one. I think it's going to be a wait and see. It is very possible there was a bug in the version which ls41 was using.. it was pretty early beta. And who knows what rate he/she had the polling set to to. 

There are too many unknowns, but i'm going to leave this open for others to chime in and post follow ups from their own experience.

Jason

**Comment by zstepek** [comment]
I'm seeing this exact issue on our site on WP Engine.
