### ISSUE TITLE
Permalink flush isn't always happening

### ISSUE THREAD

**Issue by Shelob9** [postmatic/epoch#40]
Issue #39 indicates that the necessary permalink flush is not always happening... I presume, since we havn't heard more that this is an edge case, but still.

**Comment by soderlind** [comment]
Try this, replace https://github.com/postmatic/epoch/blob/71ea40a7c73c4ceebd976a5bee643a750c8e0247/classes/core.php#L96 

with

``` php
global $wp_rewrite;
$wp_rewrite->flush_rules();
```

**Comment by Shelob9** [comment]
@soderlind Yes, that is often the best way to do it. -1 me.

I know that epoch-api, pre-this version worked properly with ugly permalinks. Which might mean that the flush never worked, but wasn't needed. Got to check if the new rewrite rule for the iFrame is in fact ugly permalinks compatible, and our flush enables that.

**Comment by soderlind** [comment]
In my [example plugin](https://soderlind.no/wordpress-plugins-and-permalinks-how-to-use-pretty-links-in-your-plugin/), I only flush if the permalink doesn't exist:

``` php
/**************************************************************************
 * Flushes the permalink structure.
 * flush_rules is an extremely costly function in terms of performance, and
 * should only be run when changing the rule.
 *
 * @see http://codex.wordpress.org/Rewrite_API/flush_rules
 **************************************************************************/
function my_permalink_flush_rewrite_rules() {
    $rules = $GLOBALS['wp_rewrite']->wp_rewrite_rules();
    if ( ! isset( $rules['my-permalink/(.*)$'] ) ) { // must be the same rule as in my_permalink_rewrite_rule($wp_rewrite)
        global $wp_rewrite;
        $wp_rewrite->flush_rules();
    }
}
```

**Comment by Shelob9** [comment]
close via a24c41f
