### ISSUE TITLE
Comments left by logged in subscribers use username 

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#41]
This one is interesting. When a comment is left by a low-level user (i tested with subscriber) the comment is posted using the username of the user. It does not use nicename, or nickname... but username.

Odd.

![screen shot 2015-08-04 at 10 41 08 am](https://cloud.githubusercontent.com/assets/80932/9063444/61b7fc24-3a95-11e5-9968-8fe6094b5047.png)

**Comment by uamv** [comment]
The issue is not isolated to low-level users. I first encountered when commenting as an admin.

**Comment by Vernal** [comment]
Interesting.I didn't run into that myself. But noted. We should have a fix in a few days.

**Comment by uamv** [comment]
Great. Thanks!

**Comment by Shelob9** [comment]
close via 77367d7
