### ISSUE TITLE
I think Epoch is conflicting with WPRocket

### ISSUE THREAD

**Issue by pwpyle62** [postmatic/epoch#43]
New user today. When Epoch is activated this fatal error message in the attached image appears in the sites footer.
When I deactivate Epoch the error disappears from the website footer. Any ideas on why and how to fix?
Paul
http://www.pancero.com
![fatal error](https://cloud.githubusercontent.com/assets/13647588/9069013/3369f3a4-3aa4-11e5-8118-1a4a5f346203.png)

**Comment by Shelob9** [comment]
Probably the same issue as #1 

Thanks for this report, we are already looking at WP Rocket related issues today.

**Comment by Vernal** [comment]
Experimenting with it right now.....

On Tue, Aug 4, 2015 at 2:38 PM, Josh Pollock notifications@github.com
wrote:

> Probably the same issue as #1
> https://github.com/postmatic/epoch/issues/1
> 
> Thanks for this report, we are already looking at WP Rocket related issues
> today.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/43#issuecomment-127706899.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Shelob9** [comment]
This is probably fixed via 30b6739, needs more testing

**Comment by Shelob9** [comment]
@pwpyle62 I have tested with all minfication on in WP Rocket and after 30b6739c0c34d771459da58a34cb90dfc3045536 I can't make this error. Closeing.

**Comment by pwpyle62** [comment]
What is 30b6739??

Paul W. Pyle

V.P. of Operations, Jim Pancero, Inc.

Phone: 208-880-3852 - Fax: 866-238-1692

paul@pancero.com

www.pancero.com

 http://bit.ly/1teOHCU Get Our Mobile APP

**Comment by Vernal** [comment]
That's Josh's way of saying he thinks we've got a fix in place, which will
ship along with 1.0.1 in the next few days :)

Jason

On Thu, Aug 6, 2015 at 9:36 PM, pwpyle62 notifications@github.com wrote:

> What is 30b6739??
> 
> Paul W. Pyle
> 
> V.P. of Operations, Jim Pancero, Inc.
> 
> Phone: 208-880-3852 - Fax: 866-238-1692
> 
> paul@pancero.com
> 
> www.pancero.com
> 
> http://bit.ly/1teOHCU Get Our Mobile APP
> 
> From: Josh Pollock [mailto:notifications@github.com]
> Sent: Thursday, August 06, 2015 6:57 PM
> To: postmatic/epoch epoch@noreply.github.com
> Cc: pwpyle62 paul@pancero.com
> Subject: Re: [epoch] I think Epoch is conflicting with WPRocket (#43)
> 
> @pwpyle62 https://github.com/pwpyle62 I have tested with all
> minfication on in WP Rocket and after <
> https://github.com/postmatic/epoch/commit/30b6739c0c34d771459da58a34cb90dfc3045536>
> 30b6739 I can't make this error. Closeing.
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/postmatic/epoch/issues/43#issuecomment-128551779> . <
> https://github.com/notifications/beacon/ANA-5EKroKTmXJqDzKeVEPJ7pVnyTsg7ks5ok_nVgaJpZM4Flhl8.gif>
> 
> ---
> 
> No virus found in this message.
> Checked by AVG - www.avg.com http://www.avg.com
> Version: 2015.0.6125 / Virus Database: 4401/10384 - Release Date: 08/06/15
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/43#issuecomment-128556891.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by pwpyle62** [comment]
OK, thanks Jason.

Paul W. Pyle

V.P. of Operations, Jim Pancero, Inc.

Phone: 208-880-3852 - Fax: 866-238-1692

paul@pancero.com

www.pancero.com

 http://bit.ly/1teOHCU Get Our Mobile APP

**Comment by pwpyle62** [comment]
8/12/2015 - New version did not get rid of the error:

Fatal error: Uncaught exception 'JSMin_UnterminatedRegExpException' with message 'JSMin: Unterminated RegExp at byte 645: /if}} ' in /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/JSMin.php:254 Stack trace: #0 /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/JSMin.php(145): JSMin->action(1) #1 /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/JSMin.php(84): JSMin->min() #2 /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/inc/front/minify.php(230): JSMin::minify('?? <div id="...') #3 [internal function]: rocket_minify_inline_js('?? <div id="...') #4 /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php(243): call_user_func('rocket_minify_i...', '?? <div id="...') #5 [internal function]: Minify_HTML->_removeScriptCB(Array) #6 /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php(105): preg_replace_callback('/(\s*)<scr in /home/panceroc/public_html/swatteamselling/wp-content/plugins/wp-rocket/min/lib/JSMin.php on line 254
