### ISSUE TITLE
Scripts in iFrame loaded via "epoch_iframe_scripts" don't get to use wp_enqueue_scripts which is bad.

### ISSUE THREAD

**Issue by Shelob9** [postmatic/epoch#51]

**Comment by Shelob9** [comment]
close via   e853dcc

**Comment by mihche** [comment]
Oh, I thought you intentionally not calling `wp_enqueue_scripts` not that this is a bug. I've explained from the beginning that `wp_enqueue_scripts` is not getting called. 
By calling `do_action( 'wp_enqueue_scripts' )` everything is simplified and we don't have to verify endpoints, etc. 
Now... I have to change my code :))
Cheers, 
Mihai
