### ISSUE TITLE
Blank comments accepted

### ISSUE THREAD

**Issue by dknauss** [postmatic/epoch#53]
Epoch (+Postmatic) allows blank comments to be submitted where no fields have been filled out when "Use my typography and colors" is selected. (Tested with a Divi 2.4.6.1 (child) theme in use, hosted with Flywheel.) Just clicking "submit" results in a comment submission whether the user is logged in or not. 

It looks like label tag content is being submitted so the comment content is "Comment" and the comment author is "Author *" -- 
![screen shot 2015-08-07 at 2 09 46 pm](https://cloud.githubusercontent.com/assets/273554/9143805/1b2d0378-3d0e-11e5-959d-c24714299560.png)

Fortunately these comments do not seem to result in the issuing of emails to Postmatic subscribers.

**Comment by Vernal** [comment]
I just made it happen using Maktab on WordPress engine (similar config).......

**Comment by Vernal** [comment]
Josh, what do you make of this?

**Comment by Shelob9** [comment]
This should be fixed in 1.0.1

**Comment by phpbits** [comment]
Hi,

Still on 1.0.1 when you just add space. I've already address this issue on AWP group before. Thanks!

Cheers,
phpbits

**Comment by Vernal** [comment]
@Shelob9 perhaps we should set a minimum number of characters required?

**Comment by dknauss** [comment]
That would help. Maybe 2-3 words minimum is better than a minimum number of
characters.

I am getting Postmatic emails now for blank comments if I submit them with
blank spaces.

_Dan Knauss_
newlocalmedia.com
design. build.. sustain...
+1 712 449-8195 ✆ +1 414 212-5628

**Comment by Vernal** [comment]
Hey Dan,

So we just realized that WordPress itself does not have a minimum. So, Epoch is no different.

You can use https://wordpress.org/plugins/minimum-comment-length/ to resolve the issue. It works already with Epoch but we're going to work on making the messaging look better.

Jason

**Comment by dknauss** [comment]
Great! I did not know this either.
