### ISSUE TITLE
Disable Epoch Commenting on Draft and pending posts

### ISSUE THREAD

**Issue by phpbits** [postmatic/epoch#54]
Hi,

How can I disable epoch and comments on draft and pending post status? I'm using it on user post submission with wp front end editor and I need to minimize the ajax calls when user is writing a post. Thanks!

Cheers,
phpbits

**Comment by Vernal** [comment]
Hey Phpbits,

Epoch would just follow suit with whatever WordPress tells it to do. My hunch is that figuring out how to tell WP to not load comments on drafts would be the solution. Maybe just an if statement added to your single.php? If status is published, then load comments?

Jason
