### ISSUE TITLE
Any hooks on how to change the profile link?

### ISSUE THREAD

**Issue by phpbits** [postmatic/epoch#55]
Hi,

Do you have any hooks for profile url? I'm using buddypress and needs to add link on profile name and avatar to go to their specific profile page. Thanks!

Cheers,
phpbits

**Comment by Vernal** [comment]
Hi Phpbits,

We do not yet but are open to you adding them. Please send along a PR if you do!

Jason

**Comment by phpbits** [comment]
Hi,

Can you point me on specific direction on how can I add it? The plugin is useless for me if I can't make the name and avatar linked to specific user profile. Thanks!

**Comment by Vernal** [comment]
Hey phpbits,

Epoch is GPL. Jump in. You can grab the code from this repo. While the js
and ajax stuff is quite complex the actual comment templates are not.

Jason

On Mon, Aug 10, 2015 at 11:30 AM, phpbits notifications@github.com wrote:

> Hi,
> 
> Can you point me on specific direction on how can I add it? The plugin is
> useless for me if I can't make the name and avatar linked to specific user
> profile. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/55#issuecomment-129496965.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Shelob9** [comment]
@phpbits Not sure what you're asking for here. Are you looking to get a different gravatar or author link then the email recorded with the comment? If so, why can't you use either `get_comment` (http://wpseek.com/hook/get_comment/) or `the_comments` (http://wpseek.com/hook/the_comments/)

**Comment by phpbits** [comment]
@Shelob9 I'm asking how can I change the avatar and name link to buddypress profile url. I can't see any buddypress plugin support so I'm asking if you have any filters available to change it. I hope it's clear now. Thanks!

Cheers,
phpbits

**Comment by Shelob9** [comment]
Right, we don't do anything special for author URL. If you filter "comment_author_url" with either of those filters in the comment data you can change it to whatever you want. This is something handled by core already handles, so no need for us to add extra hooks.

**Comment by phpbits** [comment]
@Shelob9  I tried https://codex.wordpress.org/Plugin_API/Filter_Reference/get_comment_author_link but nothing happens. It started when you updated the plugin with the fix :

Gravatars on comments without an author URL no longer link to #

I'll just find another way though. I thought you might point me on the right direction. Thanks!

**Comment by Shelob9** [comment]
I would use `get_comment` (http://wpseek.com/hook/get_comment/) or `the_comments` (http://wpseek.com/hook/the_comments/)

**Comment by phpbits** [comment]
@Shelob9  the comment author links are working fine when I deactivated the plugin. I think it's too early for me to use this one. Though I'm really impress with the plugin but it lacks plugin compatibility(such as BP and minimum comment lenght) as of the moment. Thanks!

Cheers,
phpbits
