### ISSUE TITLE
 Epoch - not ordering descending anymore

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#56]
I have just noticed that my comments are now in ascending order despite not it being set as descending in Epoch settings. I haven't changed anything, and wondering if this has happened with the recent update.

**Comment by iagdotme** [comment]
Thanks for adding this, @erscampbell
Is this confirmed? Are others experiencing this too or is it just me? I always like the comments in descending order with the comments box at the top. Now the comments are in ascending (oldest first) but the comments box is still at the top.

**Comment by iagdotme** [comment]
Is there any chance of this being fixed? It's a real problem for me as a number of my blog posts have over 500 comments and most people prefer to see the latest comments first.

**Comment by Vernal** [comment]
Hey @iagdotme i haven't been able to nail this one down yet. Is your site on a host which would allow for an easy staging site to be set up?

**Comment by iagdotme** [comment]
Thanks, @Vernal - have you seen this happening yourself or could it be just affecting me? If so, perhaps it is a plugin conflict?
I do have a dev version of my website although it's not running the same theme exactly and it's an older version. Epoch is doing the same- showing comments in ascending order despite me setting as descending.

**Comment by Vernal** [comment]
Hey Ian,

We've heard of the issue from you and one other user. Would it be possible
for you to sanitize that dev site in whatever way works for you and let us
have wp-admin?

Jason

On Tue, Aug 25, 2015 at 2:40 PM, Ian Anderson Gray <notifications@github.com

> wrote:
> 
> Thanks, @Vernal https://github.com/Vernal - have you seen this
> happening yourself or could it be just affecting me? If so, perhaps it is a
> plugin conflict?
> I do have a dev version of my website although it's not running the same
> theme exactly and it's an older version. Epoch is doing the same- showing
> comments in ascending order despite me setting as descending.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/56#issuecomment-134697019.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by iagdotme** [comment]
Jason, Yes, I can give you access no problem. It's not got all the plugins I use on the main site, but it should be able to help you. Am I best emailing you log in details?

**Comment by Vernal** [comment]
So long as it has the bug i'm happy! Sure, send it along to
jason@gopostmatic.com. Thanks so much Ian!

On Tue, Aug 25, 2015 at 2:45 PM, Ian Anderson Gray <notifications@github.com

> wrote:
> 
> Jason, Yes, I can give you access no problem. It's not got all the plugins
> I use on the main site, but it should be able to help you. Am I best
> emailing you log in details?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/56#issuecomment-134698499.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Man this is a strange deal. @iagdotme the next thing i need to test is if it is a Cloudflare issue. Can you disable Cloudflare on the dev install?

**Comment by Vernal** [comment]
Ok, I can confirm this is a problem on multiple installs. @Shelob9 sent you test server info via slack.
