### ISSUE TITLE
Optional alt endpoint for comment count check

### ISSUE THREAD

**Issue by Shelob9** [postmatic/epoch#57]

**Comment by Shelob9** [comment]
This is in 1.0.2 but not finished. Punting to 1.0.3

**Comment by ronalfy** [comment]
Not sure if this is related, if not, I'll open a new ticket.

Concerned about the absint on an array.

https://github.com/postmatic/epoch/blob/master/classes/front/api_helper.php#L421
https://github.com/postmatic/epoch/blob/master/classes/front/api_helper.php#L455

**Comment by Vernal** [comment]
Legacy. Doesn't apply to 2.0.
