### ISSUE TITLE
 Epoch issue

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#62]
Posted on behalf of Z. Jenkins:

I'm not even sure why it happens but once I tried to turn the Epoch plugin, once I tried to go to a page other than the homepage it would immediately break the site, display white only and nothing could be done on the front facing side of the site until I turned it off. I have tried it with and without Postmatic as well to the same result. I have no clue what's going on with it. My site is mygeekconfessions.com. I am on dreamhost and I know that am a couple versions back with PHP so not sure if that has something to do with it. It's a fairly small site traffic wise with few comments so not sure what could conflict with it or make it behave that way. I've also tried multiple themes to verify it wasn't the theme as well. I won't be using the plugin for now but I thought this should be addressed for your next release.

**Comment by Vernal** [comment]
I'm certain this was fixed with 1.0.2 @erscampbell.
