### ISSUE TITLE
there is no #reply-title in iframe mode

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#66]
the add a comment anchor does not work

**Comment by Vernal** [comment]
Hey @cyberhobo i'm going to assign this one to you. We need the anchor tag at the top of the iframe to actually jump to the comments.

![testing_that_thing](https://cloud.githubusercontent.com/assets/80932/9473666/080f0708-4b2a-11e5-8152-9743f3424439.png)

**Comment by cyberhobo** [comment]
This doesn't work because the iframe itself does not require scrolling to show the content:
https://bugzilla.mozilla.org/show_bug.cgi?id=638598#c13

It would have to scroll the parent frame, which would require intricate javascript in the same domain case, and would never work across domains.

Maybe we should look at moving the link outside the iframe with a link to something following it...

**Comment by Vernal** [comment]
Interesting. Ok. Research that.

On Tue, Aug 25, 2015 at 4:41 PM, Dylan Kuhn notifications@github.com
wrote:

> This doesn't work because the iframe itself does not require scrolling to
> show the content:
> https://bugzilla.mozilla.org/show_bug.cgi?id=638598#c13
> 
> It would have to scroll the parent frame, which would require intricate
> javascript in the same domain case, and would never work across domains.
> 
> Maybe we should look at moving the link outside the iframe with a link to
> something following it...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/66#issuecomment-134734167.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by cyberhobo** [comment]
That commit to branch frame-form-link sort of does it, but it's cheesy because we have to hardcode a guess at the height of the comment form, so it will probably rarely be exactly right. I'm not sure that's better than no link.

**Comment by Vernal** [comment]
Agreed. Not better than no link. Let's just go with no link. Can you make that happen?
