### ISSUE TITLE
epoch translation - de_DE & de_DE_formal as well as missing localization strings.

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#67]
Posted on behalf of R. Koller:

hi saw your contact infos in the wordpress support forums after diggin into your plugin. at first a few strings are missing a wp localization function. the ones i’ve found are in options-panel.php in lines 19, 21, 23. i dont know how you wanna proceed if you wanna make the strings inside the strong tags separate strings or place everything into one string. thats up to you otherwise i would have done it. aside i’Ve glued together an initial draft of a german localization. aside i’ve added a few po header properties you were missing in particular one which makes it possible to get the plugin header strings localized as well. aside i could add those to the pot file as well as the spanish po header as well and place a pull request on github. would just have to know how you wanna proceed with the three lines and the strong tag thing as well as i need to know against which branch i should place the pull request. 1.0.2? cheers r.

**Comment by fxbenard** [comment]
All the welcome page should be i18n ready as well

**Comment by Shelob9** [comment]
@erscampbell If you can submit a pull request against 1.0.2-dev branch to add the translation and fix the admin not having translatable strings, that would be awesome.

@Vernal -5 points for not using translatable strings.

**Comment by fxbenard** [comment]
@Vernal https://github.com/stephenharris/grunt-checktextdomain might be your new friend ;)

**Comment by Vernal** [comment]
I didn't use editable strings in admin yet because it was tending to shift a lot and there is a huge wall of text that really should be simplified. Plus, a lot of it is marketing copy for Postmatic which I'd feel bad asking others to translate for free. 

I'll try to come up with a solution by 1.1. Thanks for the tip, @fxbenard.
