### ISSUE TITLE
Add hooks to easily customize CSS for the iframe

### ISSUE THREAD

**Issue by mundschenk-at** [postmatic/epoch#85]
Currently, the cleanest looking markup is the iframe template. There should be hooks to allow developers to easily inject their own CSS (both in addition to the default stylesheet and as complete replacements).

**Comment by Vernal** [comment]
@Shelob9 does [our current method](http://docs.gopostmatic.com/article/177-loading-third-party-scripts-in-the-epoch-iframe) of loading scripts within the iframe allow for loading style sheets as well?

**Comment by mundschenk-at** [comment]
I would assume it does not, because $wp_styles is a different global object from $wp_scripts. However, a similar mechanism should be easy to implement for styles. It would be nice if the filter were to be applied after the default styles have been added (to allow developers do completely remove stylesheets they don't want to be loaded).

**Comment by Shelob9** [comment]
@Vernal No our current method does not allow for adding stylesheets. Would need to be new system, like @pep- describes.

**Comment by Vernal** [comment]
@pep- Are you interested/able to help make this happen?

**Comment by mundschenk-at** [comment]
Interested yes, able probably. I have not quite grasped the control flow in Epoch yet, and I'll have to fiddle with Composer a bit (haven't used until now).

**Comment by Shelob9** [comment]
@pep- Awesome, would love to have more people knowing their way around this. You could use a similar system to how JS is loaded, probably need to put a hook in the iFrame header for it though.

Learning Composer is going to make your life quantifiably better. Here are my resources on the subject:
http://joshpress.net/blog/composer-for-wordpress-plugin-development-on-wpsessions/
http://joshpress.net/blog/gain-wordpress-development-superpowers-with-composer/
http://joshpress.net/blog/using-composer-increase-wordpress-development-powers/

**Comment by mundschenk-at** [comment]
Thanks @Shelob9, I will have a look at those posts.

**Comment by Vernal** [comment]
Legacy. Doesn't apply to 2.0.
