### ISSUE TITLE
Evaluate and merge #89 

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#90]
Josh, can you sign off on the proposed changes on #89? I've tested it thoroughly from the user-side but want you to eyeball the code changes.

If it looks good to you please merge it into 1.0.5-dev?

Jason

**Comment by ronalfy** [comment]
Please also evaluate:
https://github.com/postmatic/epoch/issues/94
https://github.com/postmatic/epoch/issues/93

Same branch.

I won't post any more changes to this branch.
