### ISSUE TITLE
Allow hiding of track/ping backs

### ISSUE THREAD

**Issue by cklosowski** [postmatic/epoch#92]
Epoch should have an option to remove Track/Pingbacks from the comments list.

**Comment by Vernal** [comment]
have you tried any 3rd party plugins to pull this off?

**Comment by ronalfy** [comment]
I think this should be done by default. Have a filter to show them. My 2
cents.

**Comment by Vernal** [comment]
Yea. On second thought I think you are right. It makes sense that they
should be off. Thanks, Chris.

On Thu, Sep 10, 2015 at 4:16 PM, Ronald Huereca notifications@github.com
wrote:

> I think this should be done by default. Have a filter to show them. My 2
> cents.
> On Thu, Sep 10, 2015 at 14:29 Vernal notifications@github.com wrote:
> 
> > have you tried any 3rd party plugins to pull this off?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmatic/epoch/issues/92#issuecomment-139354258.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/92#issuecomment-139367423.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by cklosowski** [comment]
I set it up as an option. I did not make it on by default, as you've already released with them displaying. This means that it would alter the display to customers already using the plugin.

**Comment by cklosowski** [comment]
Big fan of opt-in to front end display changes. If you guys want it the other way though I'll update the PR.

**Comment by Vernal** [comment]
No way. Turn it off by default. Not to worried about blowback.

**Comment by cklosowski** [comment]
Ok, fair enough :)

**Comment by cklosowski** [comment]
Done. Pushed up the opt-out of hiding Pings.

**Comment by ronalfy** [comment]
+1. First thing I do on all client blogs with comments is remove
trackbacks. It confuses the crud out of them.

**Comment by Vernal** [comment]
Sweet sweet goodness. Thanks, Chris!
