### ISSUE TITLE
Improve comment permalink support

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#93]
On some sites/browsers/server configs if you try to hit a comment permalink the page may not anchor correctly because, well, the comments haven't loaded yet. 

I don't have enough info to nail down an exact scenario that does or doesn't work. Contributions welcome.

**Comment by ronalfy** [comment]
Solution would be a scroll after comments loaded. I think there may be a JS
event to hook into for that :)

**Comment by Vernal** [comment]
Think you can take it on?

On Thu, Sep 10, 2015 at 4:17 PM, Ronald Huereca notifications@github.com
wrote:

> Solution would be a scroll after comments loaded. I think there may be a JS
> event to hook into for that :)
> On Thu, Sep 10, 2015 at 14:37 Vernal notifications@github.com wrote:
> 
> > On some sites/browsers/server configs if you try to hit a comment
> > permalink the page may not anchor correctly because, well, the comments
> > haven't loaded yet.
> > 
> > I don't have enough info to nail down an exact scenario that does or
> > doesn't work. Contributions welcome.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmatic/epoch/issues/93.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/93#issuecomment-139367571.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
Yah, go ahead and assign me. But I'm presenting at wcdfw this weekend, so
if it's pressing leave it open but if the issue is still not taken care of,
I can loook at it next week.

**Comment by Vernal** [comment]
Awesome. Good luck this weekend!

**Comment by ronalfy** [comment]
Please check out https://github.com/postmatic/epoch/commit/95ef3398d4da591d82f4014f80cafdd8459753f0

I added it to the comment moderation branch since it's still under review.

I feel a little dirty with the iframe hack (your beta option), but it works.

**Comment by Vernal** [comment]
Man. Nice going. You are a rockstar Mr Heureca.

On Thu, Sep 10, 2015 at 10:51 PM, Ronald Huereca notifications@github.com
wrote:

> Please check out 95ef339
> https://github.com/postmatic/epoch/commit/95ef3398d4da591d82f4014f80cafdd8459753f0
> 
> I added it to the comment moderation branch since it's still under review.
> 
> I feel a little dirty with the iframe hack (your beta option), but it
> works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/93#issuecomment-139435661.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
