### ISSUE TITLE
Show pending (in moderation) comments on front end

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#94]
Let's display pending comments to any user with the appropriate edit_comment capability. What do you think, @ronalfy ?

**Comment by ronalfy** [comment]
Yah. Admins will freak out though when they see their post authors can see
them. Maybe just make that decision and adjust according to the blowback?

**Comment by Vernal** [comment]
Perhaps. Or maybe we make it an option to enable front-end-moderation?

On Thu, Sep 10, 2015 at 4:19 PM, Ronald Huereca notifications@github.com
wrote:

> Yah. Admins will freak out though when they see their post authors can see
> them. Maybe just make that decision and adjust according to the blowback?
> On Thu, Sep 10, 2015 at 14:44 Vernal notifications@github.com wrote:
> 
> > Let's display pending comments to any user with the appropriate
> > edit_comment capability. What do you think, @ronalfy
> > https://github.com/ronalfy ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmatic/epoch/issues/94.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/94#issuecomment-139368099.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
Let's show this by default for all appropriate permissions. We have a
winning case because they will see the same thing in the backend.

Let's include a filter to disable authors, or all, and then add options if
there is a demand for them.

**Comment by ronalfy** [comment]
Should be completed with https://github.com/postmatic/epoch/commit/4e0d0146ad20cd807ff2942edda6258bc05d60bb

Again, on the comment moderation branch since it is still under review.

Filters added to disable. Would prefer not to have a physical option here.

``` php
add_filter( 'epoch_show_unapproved', '__return_false' );    
add_filter( 'epoch_show_unapproved_authors', '__return_false' );
```

**Comment by Vernal** [comment]
Ronald, i'm at a loss for words about you and your contributions. Settle down. Wait! No! Don't settle down! Keep going!

**Comment by ronalfy** [comment]
Ha, I'll be pretty quiet for the next week very likely! :D

**Comment by Vernal** [comment]
No problem! Good luck this weekend!

On Fri, Sep 11, 2015 at 11:29 AM, Ronald Huereca notifications@github.com
wrote:

> Ha, I'll be pretty quiet for the next week very likely! :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/94#issuecomment-139576226.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
