### ISSUE TITLE
code to initialize epoch in ajax load requests

### ISSUE THREAD

**Issue by scapatina** [postmatic/epoch#98]
hello, I am wondering what the best way to implement epoch into an ajaxified site.

I need to add a function to ajaxify.js that calls epoch and loads the comments

Overall great comment plugin, Thank you!

**Comment by Vernal** [comment]
I really don't know. You'd have to experiment. You might find some info that you need over on our docs site... but really it mostly only applies to if you are running Epoch in iframe mode:
http://docs.gopostmatic.com/article/177-loading-third-party-scripts-in-the-epoch-iframe

Maybe you'll find something useful there?

Good luck!
Jason

**Comment by ronalfy** [comment]
scapatina,

Maybe you'll find this useful. It's how my plugin was able to talk to Epoch.

JS Ajax call and return: https://github.com/ronalfy/simple-comment-editing/blob/master/js/simple-comment-editing.js#L285

PHP Ajax capture/response: https://github.com/ronalfy/simple-comment-editing/blob/master/index.php#L382

You'll just have to do what I did. Dig through the code (it's actually quite organized once you get used to it) and find the appropriate API method.
